package com.francofun

// Course growth: 35 → 65 lessons. Same Phrase shape as Content/Content2
// (fr, en, sw, optional sheng/tip/grammar, CEFR level, core flag).
// Kenyan-first references throughout; Francophone-Africa culture notes.

private fun P3(fr: String, en: String, sw: String, sheng: String? = null, tip: String? = null, grammar: String? = null, level: String = "A1", core: Boolean = false) =
    Phrase(fr, en, sw, sheng, tip, grammar, level, core)

val EXTRA2_LESSONS: List<Lesson> = listOf(
    // ---------- U1 (+2 → 8) ----------
    Lesson("farewell", "👋", "Les adieux", "Saying goodbye", "Kuagana", listOf(
        P3("Au revoir !", "Goodbye!", "Kwaheri!", "Buda!", null, null, "A1", true),
        P3("À bientôt !", "See you soon!", "Tutaonana hivi karibuni!", "Tutaonana!"),
        P3("À demain !", "See you tomorrow!", "Kesho!", "Kesho msee!"),
        P3("À tout à l'heure !", "See you later today!", "Tutaonana baadaye!", "Tutaonana later!"),
        P3("Bonne journée !", "Have a good day!", "Siku njema!", "Have a njema day!"),
        P3("Bonne soirée !", "Have a good evening!", "Jioni njema!"),
        P3("Bon week-end !", "Have a good weekend!", "Wikendi njema!", "Wikendi poa!"),
        P3("Fais attention sur la route !", "Be careful on the road!", "Kuwa makini njiani!", "Jichunge kwa road!", "What every Kenyan mum says — matatu edition."),
        P3("Embrasse ta mère pour moi !", "Give your mum a hug for me!", "Nisalimie mama yako!", "Nisalimie mamako!"),
        P3("On se voit dimanche ?", "Shall we meet on Sunday?", "Tutaonana Jumapili?", "Tutaonana Sunday?"),
        P3("Je dois y aller", "I have to go", "Lazima niende", "Nabonga ufala, naenda!", null, "Devoir + infinitive = must do something.", "A1"),
        P3("Salut, à plus !", "Bye, catch you later!", "Kwaheri, tutaonana!", "Later msee!", null, null, "A1", true)
    ), "u1"),
    Lesson("titles", "🎩", "Monsieur, Madame", "Addressing people", "Kuwaita watu", listOf(
        P3("Bonjour Monsieur", "Good morning, sir", "Habari yako mzee", "Niaje mzee", "Monsieur earns you instant respect with officials.", null, "A1", true),
        P3("Bonjour Madame", "Good morning, madam", "Habari yako mama", "Niaje mama"),
        P3("Merci Monsieur", "Thank you, sir", "Asante mzee", "Asante mzee"),
        P3("Excusez-moi Madame", "Excuse me, madam", "Samahani mama", "Excuse mama", null, "Vous-form with strangers — always.", "A1"),
        P3("S'il vous plaît Monsieur", "Please, sir", "Tafadhali mzee", "Tafadhali mzee", null, null, "A1", true),
        P3("Comment allez-vous Madame ?", "How are you, madam?", "Hujambo mama?", "Uko aje mama?"),
        P3("Enchanté Monsieur", "Nice to meet you, sir", "Nimefurahi kukutana nawe mzee"),
        P3("Au revoir Madame", "Goodbye, madam", "Kwaheri mama"),
        P3("Monsieur le directeur est là ?", "Is the director in?", "Mkurugenzi yupo?", "Boss yuko?", "Handy for offices, schools, banks."),
        P3("Madame la présidente", "Madam president", "Mheshimiwa rais", null, "Titles before roles — very French administration."),
        P3("Les enfants, écoutez !", "Children, listen!", "Watoto, sikilizeni!", "Watoi, skizeni!"),
        P3("Mes amis !", "My friends!", "Marafiki zangu!", "Mabeshte!", null, "Mes + plural — possessives agree with the thing owned.", "A1")
    ), "u1"),
    // ---------- U2 (+6 → 14) ----------
    Lesson("breakfast", "🥐", "Le petit-déjeuner", "Breakfast", "Kifungua kinywa", listOf(
        P3("Tu as pris ton petit-déjeuner ?", "Did you have breakfast?", "Umekunywa chai?", "Umekunywa chai msee?", null, null, "A1", true),
        P3("Je prends du thé avec du pain", "I have tea with bread", "Nakunywa chai na mkate", "Nakunywa chai na mkate", "Partitive du/de la = some — brand-new idea for Swahili speakers.", "Du + masculine, de la + feminine.", "A1"),
        P3("Encore du chai ?", "More chai?", "Chai nyingine?", "Chai ingine?"),
        P3("Le mandazi est chaud", "The mandazi is hot", "Mandazi ni moto", "Mandazi ni moto", "Kenyan breakfast, French sentence. Win-win."),
        P3("Je préfère le café", "I prefer coffee", "Ninapendelea kahawa", "Napenda kahawa"),
        P3("Sans sucre, s'il te plaît", "Without sugar, please", "Bila sukari, tafadhali", "Bila sukari"),
        P3("Deux œufs et du jus", "Two eggs and some juice", "Mayai mawili na juisi", "Mayai mbili na juice"),
        P3("C'est délicieux !", "It's delicious!", "Ni tamu sana!", "Ni tamu!", null, null, "A1", true),
        P3("J'ai encore faim", "I'm still hungry", "Bado nina njaa", "Bado niko njaa"),
        P3("Je n'ai plus faim", "I'm not hungry anymore", "Sina njaa tena", "Nishashiba", null, "Ne…plus = not anymore.", "A1"),
        P3("On mange à quelle heure ?", "What time do we eat?", "Tunakula saa ngapi?"),
        P3("À table !", "Food's ready!", "Chakula tayari!", "Food iko ready!", null, null, "A1", true)
    ), "u2"),
    Lesson("restaurant", "🍲", "Au restaurant", "At the restaurant", "Mgahawani", listOf(
        P3("Une table pour deux", "A table for two", "Meza ya watu wawili", "Meza ya wasee wawili", null, null, "A1", true),
        P3("Le menu, s'il vous plaît", "The menu, please", "Menu, tafadhali", "Menu tafadhali"),
        P3("Qu'est-ce que vous recommandez ?", "What do you recommend?", "Mnapendekeza nini?", "Mnarecommend nini?", null, "Vous-form with waiters.", "A2"),
        P3("Je vais prendre le pilau", "I'll have the pilau", "Nitakula pilau", "Ntakula pilau", null, "Aller + infinitive = near future.", "A2"),
        P3("Et comme boisson ?", "And to drink?", "Na kinywaji?", "Na drink?"),
        P3("Un jus de mangue", "A mango juice", "Juisi ya embe", "Juice ya mango", "De = of. Jus de mangue, jus d'orange."),
        P3("C'est trop salé", "It's too salty", "Chumvi ni nyingi", "Chumvi mob"),
        P3("C'est trop pimenté !", "It's too spicy!", "Pilipili ni kali!", "Pilipili kali!", "Kenyan taste buds vs French cuisine — warn them."),
        P3("L'addition, s'il vous plaît", "The bill, please", "Bili, tafadhali", "Bill tafadhali", null, null, "A1", true),
        P3("On partage l'addition ?", "Shall we split the bill?", "Tugawane bili?", "Tusplit bill?"),
        P3("C'était excellent !", "That was excellent!", "Ilikuwa nzuri sana!", "Ilikuwa fiti!"),
        P3("On revient samedi !", "We'll be back Saturday!", "Tutarejea Jumamosi!", "Tutarudi Sato!")
    ), "u2"),
    Lesson("clothes", "👕", "Les vêtements", "Clothes", "Nguo", listOf(
        P3("J'aime ta chemise", "I like your shirt", "Ninapenda shati yako", "Shati yako ni fiti", null, null, "A1", true),
        P3("Elle est à combien cette robe ?", "How much is this dress?", "Gauni hii ni bei gani?", "Dress hii ni how much?"),
        P3("Je peux l'essayer ?", "Can I try it on?", "Naweza kuijaribu?", "Naeza itry?"),
        P3("C'est trop petit", "It's too small", "Ni ndogo sana", "Ni ndogo"),
        P3("C'est trop grand", "It's too big", "Ni kubwa sana", "Ni kubwa"),
        P3("Tu as quelle taille ?", "What size are you?", "Unavaa nambari gani?", "Size yako ni gani?"),
        P3("Le kitenge te va bien", "Kitenge suits you", "Kitenge inakupendeza", "Kitenge inakubamba", "Adjective agreement: va bien never changes — lucky break."),
        P3("J'adore ces chaussures !", "I love these shoes!", "Ninapenda viatu hivi!", "Viatu hivi ni kali!"),
        P3("C'est en solde ?", "Is it on sale?", "Iko kwa ofa?", "Iko kwa sale?"),
        P3("Je le prends !", "I'll take it!", "Ninainunua!", "Naichukua!", null, "Le/la replace the noun — pronouns before the verb.", "A2"),
        P3("Il me faut un parapluie", "I need an umbrella", "Ninahitaji mwavuli", "Nahitaji mwavuli", "April rains in Nairobi — practical French."),
        P3("Mets un pull, il fait froid !", "Put on a sweater, it's cold!", "Vaa sweta, kuna baridi!", "Vaa sweater, kuna baridi!", "Limuru mornings approved.")
    ), "u2"),
    Lesson("home", "🏡", "À la maison", "At home", "Nyumbani", listOf(
        P3("Bienvenue chez moi !", "Welcome to my place!", "Karibu kwangu!", "Karibu kwangu msee!", null, "Chez + person = at someone's place.", "A1", true),
        P3("Entre, fais comme chez toi !", "Come in, make yourself at home!", "Karibu, jisikie nyumbani!", "Ingia, feel at home!"),
        P3("Tu veux boire quelque chose ?", "Want something to drink?", "Unataka kinywaji?", "Unataka kitu ya kunywa?"),
        P3("Assieds-toi !", "Sit down!", "Keti!", "Keti chini!", "Imperative tu-form — friends and family."),
        P3("Ma chambre est petite", "My bedroom is small", "Chumba changu ni kidogo", "Room yangu ni kadogo", null, "Ma + feminine singular.", "A1"),
        P3("La cuisine est là-bas", "The kitchen is over there", "Jikoni iko kule"),
        P3("Où sont les toilettes ?", "Where is the bathroom?", "Choo kiko wapi?", "Choo iko wapi?", null, null, "A1", true),
        P3("Il n'y a pas d'eau !", "There's no water!", "Hakuna maji!", "Hakuna maji!", "Nairobi water rationing — essential vocabulary.", "Il n'y a pas de… = there is no…", "A2"),
        P3("Le courant est coupé", "The power is out", "Umeme umekatika", "Stima imeenda", "Kenya Power, meet French."),
        P3("J'habite à Kawangware", "I live in Kawangware", "Ninaishi Kawangware", "Nakaa Kawangware", null, null, "A1"),
        P3("Mon loyer est de dix mille", "My rent is ten thousand", "Kodi yangu ni elfu kumi", "Rent yangu ni thao"),
        P3("Le voisin fait du bruit !", "The neighbour is noisy!", "Jirani anapiga kelele!", "Jirani ni kelele!")
    ), "u2"),
    Lesson("sunday", "⛪", "Le dimanche", "Sundays", "Jumapili", listOf(
        P3("On va à l'église dimanche", "We go to church on Sunday", "Tunaenda kanisani Jumapili", "Tunaenda church Sunday", null, "À + le = au; à + les = aux.", "A1", true),
        P3("Le culte commence à neuf heures", "Service starts at nine", "Ibada inaanza saa tatu", "Service inaanza saa tatu", "Swahili clock! 9am = saa tatu. Bridge it!"),
        P3("Après, on mange en famille", "Afterwards we eat as a family", "Baadaye tunakula pamoja", "Baadaye tunakula na familia"),
        P3("Ma tante cuisine du chapati", "My aunt cooks chapati", "Shangazi yangu anapika chapati", "Anty anapika chapati"),
        P3("Le nyama choma est prêt !", "The nyama choma is ready!", "Nyama choma iko tayari!", "Nyama choma iko ready!"),
        P3("Qui dit la prière ?", "Who says grace?", "Nani anaomba?", "Nani anaomba kabla ya food?"),
        P3("Amen !", "Amen!", "Amina!", "Amen!"),
        P3("On regarde le match à quatre heures", "We watch the match at four", "Tunaangalia mechi saa kumi", "Tunaangalia game saa kumi", "4pm = saa kumi in Swahili time. Again!"),
        P3("Gor Mahia a gagné !", "Gor Mahia won!", "Gor Mahia imeshinda!", "Gor imeshinda!", "Football is a language. Speak it.", null, "A1"),
        P3("Quelle belle journée !", "What a beautiful day!", "Siku nzuri sana!", "Siku poa sana!"),
        P3("Merci pour le repas", "Thanks for the meal", "Asante kwa chakula", "Asante kwa food"),
        P3("À dimanche prochain !", "See you next Sunday!", "Jumapili ijayo!", "Sunday ijayo!")
    ), "u2", culture = "Sunday lunch is sacred in Kenya — and in much of Francophone Africa too, from Abidjan's attiéké gatherings to Dakar's thiéboudienne Sundays. Food first, then everything else."),
    Lesson("music", "🎶", "La musique", "Music", "Muziki", listOf(
        P3("Tu écoutes quoi en ce moment ?", "What are you listening to?", "Unasikiliza nini siku hizi?", "Unaskiza nini siku hizi?", null, null, "A1", true),
        P3("J'adore le gengetone !", "I love gengetone!", "Ninapenda gengetone!", "Gengetone ni kali!"),
        P3("Et le rap français ?", "And French rap?", "Na rap ya Kifaransa?", "Na French rap?"),
        P3("MHD est trop fort !", "MHD is so good!", "MHD ni mkali!", "MHD ni moto!", "Afro-trap: the bridge between Nairobi and Paris."),
        P3("Cette chanson est géniale", "This song is great", "Wimbo huu ni mzuri", "Ngoma hii ni kali"),
        P3("Monte le volume !", "Turn it up!", "Ongeza sauti!", "Ongeza volume!"),
        P3("Baisse un peu !", "Turn it down a bit!", "Punguza kidogo!", "Punguza kidogo!"),
        P3("Tu connais les paroles ?", "Do you know the lyrics?", "Unajua mashairi?", "Unajua lyrics?"),
        P3("On danse !", "Let's dance!", "Tucheze!", "Tudance!"),
        P3("Tu joues d'un instrument ?", "Do you play an instrument?", "Unapiga chombo?", "Unapiga instrument?", null, "Jouer de + instrument.", "A2"),
        P3("Je joue de la guitare", "I play guitar", "Ninapiga gitaa", "Napiga guitar"),
        P3("Le concert était incroyable !", "The concert was amazing!", "Tamasha lilikuwa nzuri!", "Concert ilikuwa moto!")
    ), "u2"),
    // ---------- U3 (+6 → 14) ----------
    Lesson("weekend", "🎉", "Le week-end", "Weekends", "Wikendi", listOf(
        P3("Tu fais quoi ce week-end ?", "What are you doing this weekend?", "Unafanya nini wikendi hii?", "Plans za wikendi ni gani?", null, null, "A2", true),
        P3("On va au bord du lac ?", "Shall we go to the lakeside?", "Twende ufukweni?", "Twende Naivasha?"),
        P3("Il y a une fête samedi", "There's a party Saturday", "Kuna sherehe Jumamosi", "Kuna party Sato"),
        P3("Tu viens avec nous ?", "Are you coming with us?", "Unakuja nasi?", "Unakam na sisi?", null, null, "A2", true),
        P3("Je ne peux pas, je bosse", "I can't, I'm working", "Siwezi, nina kazi", "Siwezi, nahustle"),
        P3("Tant pis !", "Too bad!", "Pole!", "Pole msee!", "Tant pis = oh well. Very French shrug-energy."),
        P3("On se voit à huit heures", "See you at eight", "Tutaonana saa mbili", "Tutaonana saa mbili", "English clock in French, Swahili clock in your head — juggle!"),
        P3("Ramène tes amis !", "Bring your friends!", "Leta marafiki zako!", "Leta mabeshte!"),
        P3("C'est où exactement ?", "Where exactly?", "Ni wapi hasa?", "Ni wapi exactly?"),
        P3("Envoie-moi la position !", "Send me the pin!", "Nitumia location!", "Nitumia pin!"),
        P3("J'arrive dans dix minutes", "I'm arriving in ten minutes", "Nafika baada ya dakika kumi", "Nafika in ten", "Kenyan ten minutes… on y croit.", null, "A2"),
        P3("C'était un super week-end !", "That was a great weekend!", "Wikendi ilikuwa nzuri!", "Wikendi ilikuwa poa!")
    ), "u3"),
    Lesson("cooking", "🍳", "En cuisine", "Cooking", "Jikoni", listOf(
        P3("Tu sais cuisiner le pilau ?", "Can you cook pilau?", "Unajua kupika pilau?", "Unajua kupika pilau?", null, "Savoir + infinitive = know how to.", "A2", true),
        P3("Coupe les oignons", "Chop the onions", "Kata vitunguu", "Kata onions"),
        P3("Ajoute du sel", "Add some salt", "Ongeza chumvi", "Ongeza chumvi"),
        P3("Mets un peu d'huile", "Put a little oil", "Weka mafuta kidogo", "Weka mafuta kidogo", "Un peu de = a little of."),
        P3("Fais bouillir l'eau", "Boil the water", "Chemsha maji", "Chemsha maji", null, "Faire + infinitive = make something happen.", "A2"),
        P3("Remue doucement", "Stir gently", "Koroga polepole", "Koroga slowly"),
        P3("Goûte !", "Taste it!", "Onja!", "Onja!"),
        P3("Il manque du sel", "It needs salt", "Chumvi imepungua", "Chumvi kidogo", "Manquer = to lack. Il manque… is gold."),
        P3("C'est presque prêt", "It's almost ready", "Inakaribia kuiva", "Inakaribia"),
        P3("Sers-toi !", "Help yourself!", "Jikaribishe!", "Jiserve!"),
        P3("Qui fait la vaisselle ?", "Who does the dishes?", "Nani anaosha vyombo?", "Nani anaosha dishes?", "The eternal Kenyan household debate.", null, "A2"),
        P3("C'était trop bon !", "That was so good!", "Ilikuwa tamu sana!", "Ilikuwa tamu!")
    ), "u3"),
    Lesson("cinema", "🎬", "Au cinéma", "At the cinema", "Sinema", listOf(
        P3("On va voir un film ?", "Shall we watch a movie?", "Twende movie?", "Twende movie?", null, null, "A2", true),
        P3("C'est quel genre ?", "What genre?", "Ni aina gani?", "Ni genre gani?"),
        P3("Une comédie française", "A French comedy", "Filamu ya kuchekesha ya Kifaransa", "Comedy ya French"),
        P3("Ça commence à quelle heure ?", "What time does it start?", "Inaanza saa ngapi?", "Inaanza saa ngapi?"),
        P3("Prenons du pop-corn !", "Let's get popcorn!", "Tunue pop-corn!", "Tuchukue popcorn!"),
        P3("Deux places, s'il vous plaît", "Two tickets, please", "Tiketi mbili, tafadhali", "Tickets mbili"),
        P3("On est bien placés", "We have good seats", "Tumekaa poa", "Tumekaa fiti"),
        P3("Chut, ça commence !", "Shh, it's starting!", "Nyamaza, inaanza!", "Shhh, inaanza!"),
        P3("Ce film fait peur !", "This movie is scary!", "Filamu hii inatisha!", "Movie hii inatisha!", null, "Faire peur = to scare.", "A2"),
        P3("J'ai pleuré à la fin", "I cried at the end", "Nililia mwishoni", "Nililia kwa ending"),
        P3("Tu as aimé ?", "Did you like it?", "Imekupendeza?", "Imekubamba?"),
        P3("On le revoit quand ?", "When do we rewatch it?", "Tutaiangalia tena lini?", "Rewatch ni lini?")
    ), "u3"),
    Lesson("exams", "📝", "Les examens", "Exams", "Mtihani", listOf(
        P3("Tu révises pour les exams ?", "Are you studying for exams?", "Unasoma kwa mtihani?", "Unarevise?", null, null, "A2", true),
        P3("J'ai un examen lundi", "I have an exam Monday", "Nina mtihani Jumatatu", "Niko na exam Monday"),
        P3("C'est sur quoi ?", "What's it on?", "Ni kuhusu nini?", "Ni about nini?"),
        P3("Tout le programme !", "The whole syllabus!", "Mada zote!", "Syllabus yote!"),
        P3("On révise ensemble ?", "Shall we study together?", "Tusome pamoja?", "Turevise pamoja?"),
        P3("Explique-moi ce chapitre", "Explain this chapter to me", "Niekeze sura hii", "Niexplain chapter hii"),
        P3("J'ai presque fini", "I'm almost done", "Ninakaribia kumaliza", "Nakaribia kumaliza"),
        P3("Courage, plus que deux jours !", "Hang in there, two days left!", "Jikaze, siku mbili tu!", "Jibambe, siku mbili!"),
        P3("Ne stresse pas !", "Don't stress!", "Usijali!", "Usistress!", "Ne + verb + pas — negation hugs the verb.", "Ne…pas with imperatives.", "A2"),
        P3("J'ai réussi !", "I passed!", "Nimefaulu!", "Nimepass!", null, "Passé composé with avoir.", "A2"),
        P3("Mention très bien !", "Top marks!", "Alama za juu!", "A plain!", "KCSE A-plain energy, en français."),
        P3("On fête ça ce soir !", "We celebrate tonight!", "Tunasherehekea leo usiku!", "Tunasherehekea leo!")
    ), "u3"),
    Lesson("news", "📰", "Les infos", "The news", "Habari", listOf(
        P3("Tu as vu les infos ?", "Did you see the news?", "Umeona habari?", "Umeona news?", null, null, "A2", true),
        P3("Il a beaucoup plu hier", "It rained a lot yesterday", "Mvua ilinyesha sana jana", "Mvua ilinyesha mob jana", null, "Passé composé with avoir.", "A2"),
        P3("Les routes sont bloquées", "The roads are blocked", "Barabara zimefungwa", "Roads zimeblock", "Nairobi rains: traffic special, en français."),
        P3("Le match est à quelle heure ?", "What time is the match?", "Mechi ni saa ngapi?", "Game ni saa ngapi?"),
        P3("On dit quoi sur le marché ?", "What's the market saying?", "Wanasemaje sokoni?", "Ground inasema aje?"),
        P3("C'est incroyable !", "That's unbelievable!", "Haiaminiki!", "Haiyawezekani!"),
        P3("Tu as entendu parler de… ?", "Have you heard about…?", "Umesikia kuhusu…?", "Umeskia kuhusu…?", null, "Entendre parler de = hear about.", "A2"),
        P3("Raconte-moi tout !", "Tell me everything!", "Niambie kila kitu!", "Niambie kila kitu!"),
        P3("C'est vrai ?", "Is that true?", "Ni kweli?", "Ni ukweli?"),
        P3("Je ne crois pas !", "I don't believe it!", "Siamini!", "Siamini!"),
        P3("On verra demain", "We'll see tomorrow", "Tutaona kesho", "Tutaona kesho", null, "Futur proche or simple — both live here.", "A2"),
        P3("Le temps passe vite !", "Time flies!", "Wakati unakwenda haraka!", "Time inaenda mbio!")
    ), "u3"),
    Lesson("proverbs", "🦉", "Proverbes", "Proverbs", "Methali", listOf(
        P3("Petit à petit, l'oiseau fait son nid", "Little by little, the bird builds its nest", "Haba na haba, hujaza kibaba", "Haba na haba!", "Your methali, but make it French. Same wisdom.", null, "A2", true),
        P3("Qui se lève tôt trouve de l'or", "Early risers find gold", "Mapema ndio best", "Mapema ndio best"),
        P3("L'union fait la force", "Unity is strength", "Umoja ni nguvu", "Umoja ni nguvu", "Motto of teamwork everywhere — Belgium included."),
        P3("Après la pluie, le beau temps", "After rain comes sunshine", "Baada ya dhiki, faraja", "Baada ya mvua, jua", "Nairobi long rains approved."),
        P3("Mieux vaut tard que jamais", "Better late than never", "Afadhali kuchelewa kuliko kukosa", "Better late!"),
        P3("Petit poisson deviendra grand", "Small fish will grow big", "Kidogo kidogo hujaza", "Hustle itakuwa kubwa", "For every campus hustler.", null, "A2"),
        P3("On ne change pas une équipe qui gagne", "Don't change a winning team", "Usivunje timu inayoshinda", "Winning team haibadilishwi"),
        P3("La nuit porte conseil", "Sleep on it", "Usiku una shauri", "Lala kwanza, decide kesho"),
        P3("Tel père, tel fils", "Like father, like son", "Mfano wa baba", "Kama baba, kama mtoi"),
        P3("Les actes parlent plus que les mots", "Actions speak louder than words", "Vitendo vina nguvu kuliko maneno", "Actions zinaongea"),
        P3("Chaque chose en son temps", "Everything in its time", "Kila jambo na wakati wake", "Kila kitu na time yake", null, null, "A2"),
        P3("La patience est une vertu", "Patience is a virtue", "Subira ni fadhila", "Subira ni key", "Matatu-queue philosophy, universal.")
    ), "u3", culture = "Methali meet proverbes: French and Swahili wisdom rhyme because both cultures farmed, fished and raised stubborn children. Trade them freely — a Kenyan who quotes French proverbs correctly earns instant delight in Dakar, Abidjan or Lyon."),
    // ---------- U4 (+6 → 11) ----------
    Lesson("bank", "🏦", "À la banque", "At the bank", "Benki", listOf(
        P3("Je veux envoyer de l'argent", "I want to send money", "Ninataka kutuma pesa", "Nadai kutuma pesa", null, null, "A2", true),
        P3("C'est comme M-Pesa ?", "Is it like M-Pesa?", "Ni kama M-Pesa?", "Ni kama M-Pesa?", "M-Pesa is the reference. Everywhere. Always."),
        P3("Quel est le code ?", "What is the code?", "Nambari ya siri ni ipi?", "Pin ni gani?"),
        P3("Je n'ai pas reçu le message", "I didn't receive the message", "Sijapokea ujumbe", "Sijapata message", null, "Ne…pas + passé composé.", "A2"),
        P3("Le réseau est lent aujourd'hui", "The network is slow today", "Mtandao ni polepole leo", "Network ni slow leo"),
        P3("Combien sont les frais ?", "What are the charges?", "Tozo ni kiasi gani?", "Charges ni how much?"),
        P3("Je veux retirer dix mille", "I want to withdraw ten thousand", "Ninataka kutoa elfu kumi", "Nadai kutoa thao"),
        P3("Voici ma carte d'identité", "Here is my ID", "Hiki kitambulisho changu", "Hii ID yangu", null, null, "A2", true),
        P3("Signez ici, s'il vous plaît", "Sign here, please", "Saini hapa, tafadhali", "Sign hapa"),
        P3("C'est fait !", "Done!", "Imekamilika!", "Done deal!"),
        P3("Gardez le reçu", "Keep the receipt", "Hifadhi risiti", "Shika receipt"),
        P3("Merci, bonne journée !", "Thanks, have a good day!", "Asante, siku njema!", "Asante, siku njema!")
    ), "u4", culture = "Mobile money runs East Africa — and French-speaking Africa has Orange Money, Wave and MTN MoMo doing the same job in Abidjan, Dakar and Douala. The vocabulary transfers directly."),
    Lesson("doctor", "🩺", "Chez le médecin", "At the doctor", "Kwa daktari", listOf(
        P3("J'ai mal à la tête", "I have a headache", "Ninaumwa na kichwa", "Kichwa inauma", "Avoir mal à = to hurt somewhere. Core pattern.", "Avoir mal à + body part.", "A2", true),
        P3("J'ai mal au ventre", "My stomach hurts", "Tumbo linauma", "Tumbo inauma"),
        P3("J'ai de la fièvre", "I have a fever", "Nina homa", "Niko na homa"),
        P3("Depuis quand ?", "Since when?", "Tangu lini?", "Tangu lini?", null, null, "A2", true),
        P3("Depuis hier soir", "Since last night", "Tangu jana usiku", "Tangu jana night", null, "Depuis + time = since.", "A2"),
        P3("Ça fait mal ici ?", "Does it hurt here?", "Inauma hapa?", "Inauma hapa?"),
        P3("Respirez profondément", "Breathe deeply", "Pumua kwa undani", "Breathe deep"),
        P3("Ouvrez la bouche", "Open your mouth", "Fungua mdomo", "Fungua mdomo"),
        P3("Prenez ce médicament deux fois par jour", "Take this medicine twice a day", "Kunywa dawa hii mara mbili kwa siku", "Kunywa dawa mara mbili"),
        P3("Buvez beaucoup d'eau", "Drink lots of water", "Kunywa maji mengi", "Kunywa maji mob"),
        P3("Reposez-vous bien", "Rest well", "Pumzika vizuri", "Rest poa", null, "Vous-form imperative.", "A2"),
        P3("Prompt rétablissement !", "Get well soon!", "Pona haraka!", "Pona poa!")
    ), "u4"),
    Lesson("salon", "💈", "Au salon", "At the barber/salon", "Kinyozi", listOf(
        P3("Une coupe, s'il vous plaît", "A haircut, please", "Nywele, tafadhali", "Cut tafadhali", null, null, "A2", true),
        P3("Pas trop court !", "Not too short!", "Si fupi sana!", "Si short sana!"),
        P3("Juste les côtés", "Just the sides", "Kando tu", "Sides tu"),
        P3("Comme sur la photo", "Like in the photo", "Kama kwenye picha", "Kama kwa picha"),
        P3("C'est combien ?", "How much?", "Ni bei gani?", "Ni how much?", null, null, "A2", true),
        P3("Tu fais des tresses ?", "Do you do braids?", "Unapiga rasta?", "Unasukuma mistari?"),
        P3("Avec de la couleur ?", "With colour?", "Na rangi?", "Na colour?"),
        P3("Ça prend combien de temps ?", "How long does it take?", "Inachukua muda gani?", "Inachukua how long?"),
        P3("Je peux attendre", "I can wait", "Ninaweza kungoja", "Naeza ngoja"),
        P3("C'est parfait, merci !", "It's perfect, thanks!", "Ni nzuri sana, asante!", "Ni fiti, asante!"),
        P3("On parle de quoi ? Du match d'hier ?", "So — yesterday's match?", "Tunaongea nini? Mechi ya jana?", "Mechi ya jana ilikuwaje?", "Salon small talk is universal. Football first."),
        P3("À la prochaine !", "See you next time!", "Wakati ujao!", "Next time!")
    ), "u4"),
    Lesson("police", "🚓", "Au poste de police", "At the police station", "Kituo cha polisi", listOf(
        P3("J'ai besoin d'aide", "I need help", "Ninahitaji msaada", "Nahitaji help", null, null, "A2", true),
        P3("On m'a volé mon téléphone", "My phone was stolen", "Nimeibiwa simu", "Nimeibiwa simu", null, "On + passive sense.", "B1"),
        P3("C'était où ?", "Where was it?", "Ilikuwa wapi?", "Ilikuwa wapi?"),
        P3("C'était quand ?", "When was it?", "Ilikuwa lini?", "Ilikuwa lini?"),
        P3("Vers huit heures du soir", "Around eight in the evening", "Kama saa mbili usiku", "Kama saa mbili usiku", "Vers = around. Softens everything."),
        P3("L'homme était grand", "The man was tall", "Mtu alikuwa mrefu", "Msee alikuwa mrefu", null, "Imparfait for descriptions.", "B1"),
        P3("Je peux faire une déclaration ?", "Can I file a report?", "Naweza kutoa taarifa?", "Naeza report?"),
        P3("Voici mon numéro", "Here is my number", "Hii nambari yangu", "Hii number yangu"),
        P3("Appelez-moi si vous trouvez quelque chose", "Call me if you find anything", "Niitieni mkipata kitu", "Nicall mkipata kitu"),
        P3("Merci pour votre aide", "Thanks for your help", "Asante kwa msaada wenu", "Asante kwa help"),
        P3("Tout va bien maintenant", "Everything is fine now", "Kila kitu kiko sawa sasa", "Kila kitu poa"),
        P3("Faites attention la nuit", "Be careful at night", "Kuwa makini usiku", "Jichunge usiku")
    ), "u4"),
    Lesson("airport", "🛫", "À l'aéroport", "At the airport", "Uwanja wa ndege", listOf(
        P3("Mon vol est à quelle heure ?", "What time is my flight?", "Ndege yangu ni saa ngapi?", "Flight yangu ni saa ngapi?", null, null, "A2", true),
        P3("C'est la porte numéro cinq", "It's gate number five", "Ni lango nambari tano", "Ni gate number tano"),
        P3("Où est l'enregistrement ?", "Where is check-in?", "Check-in iko wapi?", "Check-in iko wapi?"),
        P3("J'ai une valise et un sac", "I have a suitcase and a bag", "Nina sanduku moja na mfuko", "Niko na bag mbili"),
        P3("C'est un vol direct ?", "Is it a direct flight?", "Ni ndege ya moja kwa moja?", "Ni direct?"),
        P3("Avec escale à Addis", "With a stopover in Addis", "Kupitia Addis", "Via Addis", "Every Kenyan knows the Addis layover."),
        P3("Mon vol a du retard", "My flight is delayed", "Ndege yangu imechelewa", "Flight imedelay"),
        P3("On embarque dans dix minutes", "We board in ten minutes", "Tunapanda baada ya dakika kumi", "Boarding in ten"),
        P3("Place côté hublot !", "Window seat!", "Kiti cha dirishani!", "Window seat!", "Non-negotiable for the Rift Valley view."),
        P3("Bon voyage !", "Have a good trip!", "Safari njema!", "Safari njema!", null, null, "A2", true),
        P3("Bienvenue à Dakar !", "Welcome to Dakar!", "Karibu Dakar!", "Karibu Dakar!", "Francophone Africa awaits — Wolof optional."),
        P3("J'ai hâte de visiter !", "I can't wait to visit!", "Nasubiri kwa hamu!", "Sina subira!")
    ), "u4"),
    Lesson("hotel", "🏨", "À l'hôtel", "At the hotel", "Hoteli", listOf(
        P3("J'ai une réservation", "I have a reservation", "Nina booking", "Niko na booking", null, null, "A2", true),
        P3("Au nom de Kamau", "Under the name Kamau", "Kwa jina Kamau", "Kwa jina Kamau"),
        P3("Pour deux nuits", "For two nights", "Kwa siku mbili", "Kwa nights mbili"),
        P3("Le petit-déjeuner est inclus ?", "Is breakfast included?", "Kifungua kinywa kimo?", "Breakfast iko included?"),
        P3("Le wifi marche ?", "Does the wifi work?", "Wifi inafanya?", "Wifi inawork?"),
        P3("Quel est le code ?", "What is the code?", "Kodi ni ipi?", "Code ni gani?"),
        P3("La douche ne marche pas", "The shower doesn't work", "Shawa haifanyi kazi", "Shower haifanyi"),
        P3("Il n'y a pas de serviettes", "There are no towels", "Hakuna taulo", "Hakuna towels", null, "Il n'y a pas de…", "A2"),
        P3("À quelle heure le check-out ?", "What time is check-out?", "Kutoka ni saa ngapi?", "Check-out ni saa ngapi?"),
        P3("On peut laisser les bagages ?", "Can we leave the luggage?", "Tunaweza kuacha mizigo?", "Tunaeza wacha bags?"),
        P3("C'était un bon séjour !", "It was a good stay!", "Ilikuwa kukaa kuzuri!", "Stay ilikuwa poa!"),
        P3("Merci pour tout !", "Thanks for everything!", "Asante kwa kila kitu!", "Asante kwa kila kitu!")
    ), "u4"),
    // ---------- U5 (+6 → 11) ----------
    Lesson("sorry", "🙏", "S'excuser", "Apologizing", "Kuomba msamaha", listOf(
        P3("Pardon !", "Sorry!", "Samahani!", "Sorry!", null, null, "B1", true),
        P3("Je suis vraiment désolé", "I'm really sorry", "Nisamehe sana", "Nisamehe kabisa", "Désolé agrees: désolée if you are female."),
        P3("Toutes mes excuses", "My sincerest apologies", "Samahani sana", "My bad kabisa", "Formal — job interviews, officials.", null, "B1"),
        P3("C'est ma faute", "It's my fault", "Ni kosa langu", "Ni mistake yangu"),
        P3("Je n'ai pas fait exprès", "I didn't do it on purpose", "Sikukusudia", "Sikufanya intentionally", null, "Faire exprès = on purpose.", "B1"),
        P3("Je ne recommencerai plus", "I won't do it again", "Sitarudia tena", "Sitarudia", null, "Futur simple — promise tense.", "B1"),
        P3("Tu me pardonnes ?", "Do you forgive me?", "Unanisamehe?", "Unanisamehe?"),
        P3("Comment me faire pardonner ?", "How can I make it up?", "Nifanye nini unisamehe?", "Nifanye nini?", "The golden question after any mistake."),
        P3("Je t'invite à manger", "Dinner's on me", "Nitakualika chakula", "Food ni on me"),
        P3("On oublie tout ?", "Forget everything?", "Tusahau yote?", "Tusahau yote?"),
        P3("Merci de ta patience", "Thanks for your patience", "Asante kwa uvumilivu wako", "Asante kwa patience"),
        P3("Promis, la prochaine fois je serai à l'heure", "Promise, next time I'll be on time", "Naahidi, wakati ujao nitafika mapema", "Next time nitafika on time", "Kenyan time vs French time — negotiate.")
    ), "u5"),
    Lesson("flirt", "💘", "Draguer poliment", "Flirting politely", "Kuchati kwa heshima", listOf(
        P3("Tu as de beaux yeux", "You have beautiful eyes", "Una macho mazuri", "Una eyes poa", "Compliment, then stop. Consent is everything.", null, "B1", true),
        P3("On s'est déjà vus ?", "Have we met before?", "Tumeshakutana?", "Tumemeet before?"),
        P3("Je peux t'offrir un café ?", "Can I buy you a coffee?", "Nikununulie kahawa?", "Nikubuyie coffee?"),
        P3("Tu viens souvent ici ?", "Do you come here often?", "Unakuja hapa mara nyingi?", "Unakam huku often?"),
        P3("Tu as un beau sourire", "You have a lovely smile", "Una tabasamu nzuri", "Smile yako ni poa"),
        P3("Ça te dit qu'on se revoie ?", "Would you like to meet again?", "Ungependa tuonane tena?", "Tuonane tena?"),
        P3("Je peux avoir ton numéro ?", "Can I have your number?", "Naweza kupata nambari yako?", "Naeza pata number yako?", "Ask once. A no is a no — en français aussi."),
        P3("Pas de problème, bonne soirée !", "No problem, good evening!", "Hakuna shida, jioni njema!", "Poa, jioni njema!", "Graceful exit — the most attractive move."),
        P3("Tu me plais beaucoup", "I really like you", "Nakupenda sana", "Nakupenda", "Fort, direct, honest. Use sparingly."),
        P3("Veux-tu danser ?", "Want to dance?", "Unataka kucheza?", "Tudance?"),
        P3("Tu es magnifique ce soir", "You look stunning tonight", "Urembo leo", "Umeiva leo"),
        P3("On y va doucement", "Let's take it slow", "Twende polepole", "Twende slow", "Doucement = the most respectful word in flirting.")
    ), "u5"),
    Lesson("interview", "💼", "L'entretien", "Job interviews", "Mahojiano", listOf(
        P3("Parlez-moi de vous", "Tell me about yourself", "Niambie kuhusu wewe", "Jieleze", "The opener. Prepare 60 seconds, present tense.", null, "B1", true),
        P3("Je suis diplômé en informatique", "I graduated in IT", "Nimehitimu IT", "Nimemaliza IT"),
        P3("J'ai trois ans d'expérience", "I have three years of experience", "Nina uzoefu wa miaka mitatu", "Niko na experience ya three years"),
        P3("Pourquoi notre entreprise ?", "Why our company?", "Kwa nini kampuni yetu?", "Mbona sisi?"),
        P3("Parce que vos valeurs me parlent", "Because your values speak to me", "Kwa sababu maadili yenu yananigusa", "Values zenu ni poa"),
        P3("Quelles sont vos forces ?", "What are your strengths?", "Nguvu zako ni zipi?", "Strengths zako ni gani?"),
        P3("Je suis rigoureux et ponctuel", "I'm thorough and punctual", "Mimi ni makini na wa wakati", "Mimi ni serious na punctual", "Adjectives agree with YOU: rigoureuse if female."),
        P3("Et vos faiblesses ?", "And your weaknesses?", "Na udhaifu wako?", "Na weaknesses?"),
        P3("Je travaille trop — voilà ma faiblesse", "I work too much — that's my weakness", "Ninafanya kazi sana", "Nahustle sana", "The classic. They know. You know. Say it anyway."),
        P3("Quelles sont vos prétentions ?", "What are your salary expectations?", "Mshahara unaotaka ni?", "Salary expectation ni?"),
        P3("Quand pouvez-vous commencer ?", "When can you start?", "Unaweza kuanza lini?", "Unaeza start lini?", null, "Pouvoir + infinitive.", "B1"),
        P3("Merci pour cette opportunité", "Thanks for this opportunity", "Asante kwa nafasi hii", "Asante kwa chance hii")
    ), "u5", culture = "In France and Francophone Africa, interviews run on vous, firm handshakes (or a nod in Dakar), and zero slang — save the verlan for after you're hired. Punctuality is the first test: arrive ten minutes early."),
    Lesson("meetup", "🤝", "La rencontre", "Meeting someone", "Kukutana na mtu", listOf(
        P3("Salut ! Moi c'est Brian", "Hi! I'm Brian", "Habari! Mimi ni Brian", "Niaje! Mimi ni Brian", null, null, "B1", true),
        P3("Enchanté !", "Nice to meet you!", "Nimefurahi!", "Poa kukumeet!"),
        P3("Tu es d'où ?", "Where are you from?", "Unatoka wapi?", "Unatoka wapi?"),
        P3("Je suis de Nakuru", "I'm from Nakuru", "Ninatoka Nakuru", "Nimetoka Nakuru"),
        P3("Tu fais quoi dans la vie ?", "What do you do?", "Unafanya kazi gani?", "Unafanya nini life?"),
        P3("Je suis étudiant en médecine", "I'm a med student", "Mimi ni mwanafunzi wa udaktari", "Nasomea medicine"),
        P3("Et toi, tu viens souvent ici ?", "And you, come here often?", "Na wewe, unakuja hapa mara nyingi?", "Na wewe, unakam huku?"),
        P3("On échange nos numéros ?", "Shall we swap numbers?", "Tubadilishane nambari?", "Tubadilishane numbers?"),
        P3("C'était super de te rencontrer !", "So great meeting you!", "Nimefurahi kukutana nawe!", "Poa kukumeet!"),
        P3("On se revoit bientôt, j'espère", "Hope to see you again soon", "Natumai tutaonana hivi karibuni", "Tutaonana soon"),
        P3("Fais attention en rentrant !", "Get home safe!", "Fika salama!", "Fika salama!"),
        P3("Bonne nuit !", "Good night!", "Usiku mwema!", "Usiku mwema!")
    ), "u5"),
    Lesson("wedding", "💒", "Au mariage", "At a wedding", "Harusi", listOf(
        P3("Félicitations aux mariés !", "Congratulations to the couple!", "Hongera kwa bwana na bibi harusi!", "Congrats kwa couple!", null, null, "B1", true),
        P3("La mariée est magnifique", "The bride is stunning", "Bibi harusi ni mrembo", "Bride ni mrembo"),
        P3("Le marié a bien de la chance", "The groom is lucky", "Bwana harusi ana bahati", "Groom ako lucky"),
        P3("La cérémonie était émouvante", "The ceremony was moving", "Sherehe iligusa moyo", "Ceremony ilinigusa", null, "Imparfait for atmosphere.", "B1"),
        P3("On danse toute la nuit !", "We dance all night!", "Tunacheza usiku mzima!", "Tunadance all night!"),
        P3("Tu connais la famille ?", "Do you know the family?", "Unawajua familia?", "Unajua familia?"),
        P3("Je suis un ami du marié", "I'm a friend of the groom", "Mimi ni rafiki wa bwana harusi", "Mimi ni beshte wa groom"),
        P3("Le buffet est incroyable", "The buffet is amazing", "Chakula ni kingi!", "Buffet ni moto!", "Kenyan weddings: nobody leaves hungry. Same in Abidjan."),
        P3("Encore du nyama choma !", "More nyama choma!", "Nyama choma zaidi!", "Nyama tena!"),
        P3("Vive les mariés !", "Long live the couple!", "Waishi bwana na bibi harusi!", "Long live couple!", "Vive + noun = long live…"),
        P3("On leur offre quoi ?", "What do we gift them?", "Tunawapa zawadi gani?", "Gift ni gani?", "M-Pesa 'sadaka ya harusi' works in French too: une enveloppe."),
        P3("C'était une belle fête !", "What a party!", "Sherehe nzuri!", "Party ilikuwa poa!")
    ), "u5", culture = "Kenyan weddings feed hundreds; Senegalese and Ivorian weddings feed hundreds AND hire a griot for praise-singing. Bring an envelope, dance badly, compliment the aunties — in any language, you're family now."),
    Lesson("derby", "⚽", "Le derby", "Football talk", "Mechi", listOf(
        P3("Tu supportes quelle équipe ?", "Which team do you support?", "Unashabikia timu gani?", "Team yako ni gani?", null, null, "B1", true),
        P3("Gor Mahia, bien sûr !", "Gor Mahia, obviously!", "Gor Mahia, bila shaka!", "Gor, bila doubt!"),
        P3("Le mien, c'est l'OM", "Mine is Marseille", "Yangu ni Marseille", "Mimi ni OM", "Pick a French club. Marseille = chaos, PSG = money. Choose wisely."),
        P3("On a gagné deux à zéro !", "We won two-nil!", "Tulishinda mbili bila!", "Tulishinda two-nil!"),
        P3("L'arbitre était aveugle !", "The ref was blind!", "Mwamuzi alikuwa kipofu!", "Ref alikuwa blind!", "Universal football truth, every language."),
        P3("C'était un penalty évident !", "That was a clear penalty!", "Ilikuwa penalti wazi!", "Ilikuwa penalty clear!"),
        P3("Ton équipe joue mal en ce moment", "Your team is playing badly lately", "Timu yako inacheza vibaya siku hizi", "Team yako inacheza vibaya", "Say with a grin. Run afterwards.", null, "B1"),
        P3("Pas vraiment, on est premiers !", "Not really, we're top!", "Sio kweli, tuko wa kwanza!", "Si ukweli, tuko top!"),
        P3("Mais je pense que le coach doit partir", "But I think the coach must go", "Lakini nadhani kocha aende", "Lakini coach afutwe"),
        P3("On parie ? Le perdant paie le déjeuner !", "Bet? Loser buys lunch!", "Tuweke dau? Aliyeshindwa anunue lunch!", "Bet? Loser analipa lunch!"),
        P3("Que le meilleur gagne !", "May the best win!", "Bora ashinde!", "Best team ishinde!", null, "Subjonctif spotted: gagne.", "B1"),
        P3("Prochain match, on y va ensemble !", "Next match, we go together!", "Mechi ijayo, twende pamoja!", "Next game twende pamoja!")
    ), "u5"),
    // ---------- U6 (+4 → 6, B1 capstone) ----------
    Lesson("b1chat", "💬", "Conversation B1", "Fluent small talk", "Mazungumzo B1", listOf(
        P3("Alors, quoi de neuf depuis hier ?", "So, what's new since yesterday?", "Kuna nini mpya tangu jana?", "Kuna nini mpya?", null, null, "B1", true),
        P3("Pas grand-chose, et toi ?", "Not much, you?", "Hakuna kipya, na wewe?", "Hakuna much, na wewe?"),
        P3("J'ai passé la journée à bosser", "I spent the day working", "Nimetumia siku nikifanya kazi", "Siku nzima nimehustle", null, "Passé composé: j'ai passé.", "B1"),
        P3("Et demain, tu as prévu quoi ?", "And tomorrow, what's planned?", "Na kesho, umepanga nini?", "Na kesho, plans ni gani?", null, "Futur proche implied.", "B1"),
        P3("Je vais voir un ami", "I'm going to see a friend", "Nitaonana na rafiki", "Nitaonana na beshte"),
        P3("Ça fait longtemps !", "It's been a while!", "Muda mrefu!", "Long time!"),
        P3("On s'est perdus de vue", "We lost touch", "Tulipotezana", "Tulipotezana", null, "Se perdre — pronominal past.", "B1"),
        P3("Il faut qu'on se voie plus souvent", "We must meet more often", "Tunapaswa kuonana mara nyingi", "Tuonane more often", null, "Falloir que + subjonctif.", "B1"),
        P3("Carrément !", "Totally!", "Kabisa!", "Kabisa!"),
        P3("Bon, je file, on s'appelle !", "Right, I'm off, let's call!", "Sawa, naenda, tupigiane!", "Sawa, naenda, tucall!"),
        P3("Vas-y, à plus tard !", "Go on, see you later!", "Sawa, baadaye!", "Sawa, later!"),
        P3("Passe le bonjour à ta sœur !", "Say hi to your sister!", "Nisalimie dada yako!", "Nisalimie siz yako!")
    ), "u6"),
    Lesson("b1past", "⏳", "Raconter au passé", "Telling past stories", "Kusimulia yaliyopita", listOf(
        P3("Hier, je suis allé au marché", "Yesterday I went to the market", "Jana nilienda sokoni", "Jana nilienda market", null, "Aller takes être — agreement time.", "B1", true),
        P3("Elle est venue avec moi", "She came with me", "Alikuja nami", "Alikuja na mimi", null, "Venir takes être; -e for feminine.", "B1"),
        P3("On a beaucoup rigolé", "We laughed a lot", "Tulicheka sana", "Tulicheka mob", null, "Avoir for most verbs.", "B1"),
        P3("Il faisait beau", "The weather was nice", "Hali ya hewa ilikuwa nzuri", "Weather ilikuwa poa", null, "Imparfait for background.", "B1"),
        P3("Tout à coup, il a commencé à pleuvoir", "Suddenly it started raining", "Ghafla mvua ilianza", "Ghafla mvua ikaanza"),
        P3("On a couru jusqu'au bus", "We ran to the bus", "Tulikimbia hadi basi", "Tulikimbia hadi bus"),
        P3("Heureusement, on l'a eu !", "Luckily we caught it!", "Kwa bahati nzuri tulipata!", "Bahati tulipata!"),
        P3("Et toi, ta journée ?", "And you, your day?", "Na wewe, siku yako?", "Na wewe, day yako?"),
        P3("Raconte-moi tout !", "Tell me everything!", "Niambie kila kitu!", "Niambie kila kitu!"),
        P3("C'était une journée parfaite", "It was a perfect day", "Ilikuwa siku kamili", "Ilikuwa siku fiti", null, "C'était = imparfait of être.", "B1"),
        P3("On recommence demain ?", "Same again tomorrow?", "Turudie kesho?", "Repeat kesho?"),
        P3("Avec plaisir !", "With pleasure!", "Kwa furaha!", "Na furaha!")
    ), "u6"),
    Lesson("b1debate", "🗣️", "Débattre niveau B1", "Arguing well", "Kujadili B1", listOf(
        P3("Je ne suis pas d'accord", "I disagree", "Sikubaliani", "Sikubali", null, null, "B1", true),
        P3("À mon avis, c'est trop cher", "In my opinion it's too pricey", "Kwa maoni yangu, ni ghali", "Kwa opinion yangu, ni expensive"),
        P3("Tu as raison sur ce point", "You're right on that point", "Uko sahihi hapo", "Uko right hapo"),
        P3("Mais d'un autre côté…", "But on the other hand…", "Lakini kwa upande mwingine…", "Lakini on the other hand…", "Debate glue. Memorize it.", null, "B1"),
        P3("Prenons un exemple", "Take an example", "Tuchukue mfano", "Example moja"),
        P3("Les faits sont clairs", "The facts are clear", "Ukweli uko wazi", "Facts ziko clear"),
        P3("Tu exagères un peu !", "You're exaggerating a bit!", "Unazidisha kidogo!", "Unazidisha!"),
        P3("Peut-être, mais écoute…", "Maybe, but listen…", "Labda, lakini sikiza…", "Maybe, lakini skiza…"),
        P3("On est d'accord sur l'essentiel", "We agree on the essentials", "Tunakubaliana kwa muhimu", "Tunakubaliana kwa basics"),
        P3("Restons bons amis !", "Let's stay good friends!", "Tubaki marafiki!", "Tubaki mabeshte!", "Every French debate ends here. Every one."),
        P3("Tu m'as convaincu !", "You've convinced me!", "Umenishawishi!", "Umeniconvince!", null, "Convaincre — great B1 verb.", "B1"),
        P3("On en reparle demain", "We'll talk again tomorrow", "Tutaongea tena kesho", "Tutaongea tena kesho")
    ), "u6"),
    Lesson("b1future", "🚀", "Projets d'avenir", "Future plans", "Mipango ya baadaye", listOf(
        P3("L'année prochaine, je vais voyager", "Next year I'm going to travel", "Mwaka ujao nitasafiri", "Next year ntatravel", null, "Aller + infinitive = futur proche.", "B1", true),
        P3("Je vais apprendre le wolof aussi", "I'm going to learn Wolof too", "Nitafunza Wolof pia", "Nitafunza Wolof pia", "Dakar plans need Wolof. French first."),
        P3("Tu vas faire quoi après les études ?", "What will you do after studies?", "Utafanya nini baada ya masomo?", "After campus utafanya nini?"),
        P3("Je vais chercher du travail à Kigali", "I'll look for work in Kigali", "Nitatafuta kazi Kigali", "Nitatafuta job Kigali", "Francophone job market — real opportunity.", null, "B1"),
        P3("Et si ça ne marche pas ?", "And if it doesn't work?", "Na isipofanyika?", "Na ikianguka?"),
        P3("J'aurai toujours le français !", "I'll always have French!", "Nitakuwa na Kifaransa!", "French itabaki!", null, "Futur simple: j'aurai.", "B1"),
        P3("Le français ouvre des portes", "French opens doors", "Kifaransa kinafungua milango", "French inafungua doors"),
        P3("Dans cinq ans, je me vois à Abidjan", "In five years I see myself in Abidjan", "Baada ya miaka mitano, najiona Abidjan", "In five years niko Abidjan"),
        P3("Il faut juste continuer", "You just have to keep going", "Lazima tuendelee", "Tuendelee tu", null, "Falloir = necessity.", "B1"),
        P3("Petit à petit !", "Little by little!", "Haba na haba!", "Haba na haba!"),
        P3("Quel est ton rêve ?", "What is your dream?", "Ndoto yako ni ipi?", "Dream yako ni gani?"),
        P3("Mon rêve, c'est de parler couramment", "My dream is to speak fluently", "Ndoto yangu ni kuongea vizuri", "Dream yangu ni kuflow")
    ), "u6", culture = "Why French matters for a Kenyan: Alliance Française Nairobi, degree programs in Dakar, Abidjan and Kigali, and regional bodies that work in French and English. A Kenyan who speaks real French skips a hundred queues."),
    Lesson("sounds", "🔊", "Les sons", "French sounds", "Matamshi", listOf(
        P3("Un bonbon blanc", "A white sweet", "Pipi nyeupe", "Sweet nyeupe", "Nasals: un/on/an. Hum them — nose does the work.", null, "A1", true),
        P3("Tu ou tout ?", "You or all?", "Wewe au yote?", "Wewe ama yote?", "Minimal pair #1: tu/tout. Ear training starts here."),
        P3("Où ou ou ?", "Where or or?", "Wapi au au?", "Wapi ama or?", "Où (where) wears a hat. Ou (or) doesn't."),
        P3("Le petit pain au lait", "The small milk bread", "Mkate mdogo wa maziwa", "Mkate wa maziwa", "Pain/bain, rue/roue — same game."),
        P3("Je roule en roue libre", "I coast along", "Ninaenda bila shida", "Naenda free", "French R: gargle gently. No one masters it day one."),
        P3("Écoute et répète", "Listen and repeat", "Sikiliza na urudie", "Skiza na urudie", null, null, "A1", true),
        P3("Encore une fois, lentement", "Once more, slowly", "Tena, polepole", "Tena, slowly"),
        P3("Les lettres muettes", "Silent letters", "Herufi zisizosomwa", "Silent letters", "The s, t, d at word ends? Usually silent. Free gift."),
        P3("Et, est, es : ça se prononce pareil !", "Et/est/es sound the same", "Zote zinasikika sawa", "Zote same", "Homophones everywhere — context is king.", null, "A1"),
        P3("Fais la liaison : les‿amis", "Link it: les‿amis", "Unganisha: les amis", "Link les-amis", "Liaison: the s wakes up before a vowel."),
        P3("Ça va mieux comme ça", "That's better like that", "Hivyo ni bora", "Hivyo ni poa", "Ç always says 'ss'. No exceptions."),
        P3("Parfait, on continue !", "Perfect, let's continue!", "Nzuri, tuendelee!", "Perfect, tuendelee!")
    ), "u1", culture = "Nasal vowels (an, on, in) don't exist in Swahili or English — your nose learns a new trick. Francophone Africans from Dakar to Kinshasa all nail them; so will you, one bonbon at a time.")
    // __APPEND_POINT2__
)

