package com.francofun

// Content7: Unit 13 (Banque quotidienne — everyday phrase bank, batch 1).
// Situational two-clause sentences for daily revision. Additive only.

val EXTRA6_LESSONS: List<Lesson> = listOf(
    Lesson("b-market", "🧺", "Au marché", "Market phrases", "Sokoni", listOf(
        Phrase("Le bus de sept heures est toujours en retard", "The 7 o'clock bus is always late", "Basi ya saa moja inachelewaga", "Bus ya saa moja huchelewa"),
        Phrase("Les tomates ont augmenté cette semaine", "Tomatoes went up this week", "Nyanya zimepanda wiki hii", null, null, null, "A2"),
        Phrase("Je prends deux kilos de sucre", "I'll take two kilos of sugar", "Natae kilo mbili za sukari", null, null, null, "A1"),
        Phrase("Vous acceptez le mobile money ?", "Do you take mobile money?", "Unakubali malipo ya simu?", "Unakubali M-Pesa?", null, null, "A2"),
        Phrase("Faites-moi un petit prix, s'il vous plaît", "Give me a small price, please", "Nipunguzie kidogo, tafadhali", null, null, null, "A2"),
        Phrase("Les mangues sont mûres aujourd'hui", "The mangoes are ripe today", "Maembe yameiva leo", null, null, null, "A1"),
        Phrase("Je reviendrai samedi prochain", "I'll come back next Saturday", "Nitarudi Jumamosi ijayo", null, null, null, "A2"),
        Phrase("C'est frais du matin", "It's fresh from this morning", "Ni freshi za asubuhi", null, null, null, "A1"),
        Phrase("Pesez-moi un kilo d'oignons", "Weigh me a kilo of onions", "Nipimie kilo moja ya vitunguu", null, null, null, "A2"),
        Phrase("J'ai oublié mon panier à la maison", "I forgot my basket at home", "Nimesahau kikapu nyumbani", null, null, null, "A2"),
        Phrase("Les œufs sont à quel prix ?", "How much are the eggs?", "Mayai ni bei gani?", null, null, null, "A1"),
        Phrase("Gardez la monnaie, merci", "Keep the change, thanks", "Baki na chenji, asante", null, null, null, "A1"),
        Phrase("On se voit au même endroit", "See you at the same spot", "Tutaonana pahala pale", null, null, null, "A2"),
        Phrase("Le maïs est encore vert", "The corn is still green", "Mahindi bado mabichi", null, null, null, "A2"),
        Phrase("Bon marché et bonne journée !", "Good market and good day!", "Soko njema na siku njema!", null, null, null, "A1")
    ), "u13"),
    Lesson("b-transport", "🚌", "Transport", "Getting around phrases", "Usafiri", listOf(
        Phrase("Le matatu est déjà plein", "The matatu is already full", "Mathree imejaa", "Mathree imejaa"),
        Phrase("Le chauffeur roule trop vite", "The driver drives too fast", "Dereva anaendesha haraka sana", null, null, null, "A2"),
        Phrase("Je descends au prochain arrêt", "I'm getting off at the next stop", "Ninashuka kituo kijacho", "Nashuka next stage", null, null, "A2"),
        Phrase("Combien jusqu'en ville ?", "How much to town?", "Hadi mjini ni ngapi?", null, null, null, "A1"),
        Phrase("Poussez-vous un peu, s'il vous plaît", "Squeeze a bit, please", "Songeni kidogo, tafadhali", null, null, null, "A2"),
        Phrase("La route est bloquée à cause des travaux", "The road is blocked due to works", "Barabara imefungwa kwa sababu ya ujenzi", null, null, null, "B1"),
        Phrase("J'ai raté la correspondance de huit heures", "I missed the eight o'clock connection", "Nimekosa gari la saa mbili", null, null, null, "B1"),
        Phrase("Le boda arrive dans cinq minutes", "The boda arrives in five minutes", "Boda inakuja baada ya dakika tano", null, null, null, "A2"),
        Phrase("Mettez la ceinture, s'il vous plaît", "Put the belt on, please", "Funga mkanda, tafadhali", null, null, null, "A2"),
        Phrase("On est coincés dans les bouchons", "We're stuck in traffic", "Tumekwama kwa foleni", "Tumekwama kwa jam", null, null, "A2"),
        Phrase("Le train part du quai numéro deux", "The train leaves from platform two", "Treni inaondoka jukwaa nambari mbili", null, null, null, "B1"),
        Phrase("Mon vol a deux heures de retard", "My flight is two hours late", "Ndege yangu imechelewa masaa mawili", null, null, null, "B1"),
        Phrase("Où est la station de taxis ?", "Where is the taxi stand?", "Stendi ya teksi iko wapi?", null, null, null, "A1"),
        Phrase("Je préfère marcher, c'est tout près", "I prefer walking, it's very close", "Napendelea kutembea, ni karibu sana", null, null, null, "A2"),
        Phrase("Arrêtez-moi ici, merci", "Stop me here, thanks", "Nisimamishie hapa, asante", null, null, null, "A2")
    ), "u13"),
    Lesson("b-home", "🏠", "À la maison", "Home phrases", "Nyumbani", listOf(
        Phrase("J'ai perdu les clés de la maison", "I lost the house keys", "Nimepoteza funguo za nyumba", null, null, null, "A2"),
        Phrase("La coupure a duré trois heures", "The blackout lasted three hours", "Umeme ulikatika kwa masaa matatu", "Stima ilikatika masaa matatu", null, null, "B1"),
        Phrase("Le robinet fuit dans la cuisine", "The tap leaks in the kitchen", "Bomba linavuja jikoni", null, null, null, "B1"),
        Phrase("Maman prépare le dîner", "Mum is making dinner", "Mama anaandaa chakula cha jioni", null, null, null, "A1"),
        Phrase("Éteins la lumière en sortant", "Turn the light off when leaving", "Zima taa ukitoka", null, null, null, "A2"),
        Phrase("Le bébé dort dans sa chambre", "The baby sleeps in his room", "Mtoto amelala chumbani kwake", null, null, null, "A1"),
        Phrase("On mange devant la télé ce soir", "We're eating in front of the TV tonight", "Tunakula mbele ya TV leo", null, null, null, "A2"),
        Phrase("Le toit fuit quand il pleut", "The roof leaks when it rains", "Paa linavuja mvua ikinyesha", null, null, null, "B1"),
        Phrase("Range ta chambre avant de sortir", "Tidy your room before going out", "Panga chumba chako kabla ya kutoka", null, null, null, "A2"),
        Phrase("Le chien aboie toute la nuit", "The dog barks all night", "Mbwa anabweka usiku kucha", null, null, null, "A2"),
        Phrase("Papa répare la porte du salon", "Dad is fixing the living-room door", "Baba anatengeneza mlango wa sebule", null, null, null, "A2"),
        Phrase("Il n'y a plus d'eau dans le réservoir", "There's no more water in the tank", "Hakuna maji tena kwenye tenki", null, null, null, "B1"),
        Phrase("Les voisins font trop de bruit", "The neighbours make too much noise", "Majirani wanapiga kelele sana", null, null, null, "A2"),
        Phrase("Ferme la porte à clé", "Lock the door", "Funga mlango kwa kufuli", null, null, null, "A1"),
        Phrase("La maison sent le chapati chaud", "The house smells of hot chapati", "Nyumba inanukia chapati moto", null, null, null, "A2")
    ), "u13"),
    Lesson("b-school", "🎒", "À l'école", "School phrases", "Shuleni", listOf(
        Phrase("Le prof de maths est absent", "The maths teacher is absent", "Mwalimu wa hisabati hayupo", null, null, null, "A2"),
        Phrase("J'ai oublié mon cahier de français", "I forgot my French notebook", "Nimesahau daftari la Kifaransa", null, null, null, "A2"),
        Phrase("L'examen commence à huit heures pile", "The exam starts at eight sharp", "Mtihani unaanza saa mbili kamili", null, null, null, "A2"),
        Phrase("On a cours de chimie après la pause", "We have chemistry after break", "Tuna somo la kemia baada ya mapumziko", null, null, null, "A2"),
        Phrase("La cloche a déjà sonné", "The bell already rang", "Kengele imeshalia", null, null, null, "A1"),
        Phrase("Prête-moi ton stylo rouge", "Lend me your red pen", "Nikopeshe kalamu nyekundu", null, null, null, "A2"),
        Phrase("Le surveillant fait sa ronde", "The supervisor is doing rounds", "Msimamizi anazunguka", null, null, null, "B1"),
        Phrase("Nos résultats sortent vendredi", "Our results come out Friday", "Matokeo yetu yanatoka Ijumaa", null, null, null, "A2"),
        Phrase("Je révise avec mes voisins de table", "I revise with my deskmates", "Ninasoma na wenzangu wa dawati", null, null, null, "A2"),
        Phrase("La bibliothèque ferme à dix-sept heures", "The library closes at five", "Maktaba inafungwa saa kumi na moja", null, null, null, "B1"),
        Phrase("Le match inter-écoles, c'est samedi", "The inter-school match is Saturday", "Mechi ya shule ni Jumamosi", null, null, null, "A2"),
        Phrase("J'ai eu dix-huit en dictée", "I got eighteen in dictation", "Nimepata kumi na nane kwenye imla", null, null, null, "B1"),
        Phrase("Le directeur veut nous voir", "The principal wants to see us", "Mkuu anataka kutuona", null, null, null, "A2"),
        Phrase("On a congé lundi prochain", "We're off next Monday", "Tuko likizo Jumatatu ijayo", null, null, null, "A2"),
        Phrase("Rangez vos copies, le temps est écoulé", "Put away your papers, time is up", "Wekeni karatasi, muda umeisha", null, null, null, "B1")
    ), "u13"),
    Lesson("b-church", "⛪", "À l'église", "Church phrases", "Kanisani", listOf(
        Phrase("Le culte commence à dix heures", "The service starts at ten", "Ibada inaanza saa nne", null, null, null, "A2"),
        Phrase("La chorale chante très bien", "The choir sings very well", "Kwaya inaomba vizuri", "Choir inaomba fiti", null, null, "A1"),
        Phrase("Le pasteur lit un psaume", "The pastor reads a psalm", "Mchungaji anasoma zaburi", null, null, null, "B1"),
        Phrase("Asseyons-nous devant, près de l'autel", "Let's sit in front, near the altar", "Tuketi mbele, karibu na madhabahu", null, null, null, "A2"),
        Phrase("La quête passe dans dix minutes", "The collection comes in ten minutes", "Sadaka inapita baada ya dakika kumi", null, null, null, "B1"),
        Phrase("Le sermon parle du pardon", "The sermon is about forgiveness", "Mahubiri yanahusu msamaha", null, null, null, "B1"),
        Phrase("Chantons le cantique numéro douze", "Let's sing hymn number twelve", "Tuimbe wimbo nambari kumi na mbili", null, null, null, "A2"),
        Phrase("Le baptême aura lieu dimanche", "The baptism takes place Sunday", "Ubatizo utafanyika Jumapili", null, null, null, "B1"),
        Phrase("Prions pour les malades", "Let's pray for the sick", "Tuwaombee wagonjwa", null, null, null, "A2"),
        Phrase("La messe finit à midi pile", "Mass ends at noon sharp", "Misa inaisha adhuhuri kamili", null, null, null, "A2"),
        Phrase("Que Dieu vous bénisse tous", "God bless you all", "Mungu awabariki wote", null, null, null, "A1"),
        Phrase("Les enfants vont à l'école du dimanche", "The children go to Sunday school", "Watoto wanaenda shule ya Jumapili", null, null, null, "A2"),
        Phrase("Le mariage commence à quatorze heures", "The wedding starts at two", "Harusi inaanza saa nane", null, null, null, "A2"),
        Phrase("Après le culte, on partage le thé", "After service, we share tea", "Baada ya ibada, tunashiriki chai", null, null, null, "A2"),
        Phrase("Amen, que sa volonté soit faite", "Amen, may His will be done", "Amina, mapenzi yake yatimizwe", null, null, null, "B1")
    ), "u13"),
    Lesson("b-football", "⚽", "Le foot", "Football phrases", "Mpira", listOf(
        Phrase("Le match commence à quinze heures", "The match starts at three", "Mechi inaanza saa tisa", null, null, null, "A2"),
        Phrase("L'arbitre a sifflé un penalty", "The ref whistled a penalty", "Mwamuzi amepuliza penati", null, null, null, "B1"),
        Phrase("Notre gardien a tout arrêté", "Our keeper saved everything", "Kipa wetu ameokoa kila kitu", null, null, null, "B1"),
        Phrase("Quel but magnifique à la dernière minute !", "What a stunning last-minute goal!", "Goli zuri dakika za mwisho!", null, null, null, "A2"),
        Phrase("Les supporters chantent sans arrêt", "The fans sing non-stop", "Mashabiki wanaimba bila kukoma", null, null, null, "A2"),
        Phrase("C'était hors-jeu, clairement", "It was offside, clearly", "Ilikuwa nje, wazi", null, null, null, "B1"),
        Phrase("On a gagné deux à zéro", "We won two-nil", "Tumeshinda mbili bila", "Tumeshinda mbili bila", null, null, "A2"),
        Phrase("La revanche, c'est dimanche prochain", "The rematch is next Sunday", "Marudiano ni Jumapili ijayo", null, null, null, "B1"),
        Phrase("Il a reçu un carton jaune", "He got a yellow card", "Amepata kadi ya njano", null, null, null, "B1"),
        Phrase("La prolongation dure trente minutes", "Extra time lasts thirty minutes", "Muda wa ziada ni dakika thelathini", null, null, null, "B1"),
        Phrase("Les tirs au but décident tout", "Penalties decide everything", "Penati zinaamua kila kitu", null, null, null, "B1"),
        Phrase("Notre capitaine s'est blessé", "Our captain got injured", "Nahodha wetu ameumia", null, null, null, "B1"),
        Phrase("Le stade était plein à craquer", "The stadium was packed", "Uwanja ulikuwa umejaa", null, null, null, "B1"),
        Phrase("On chante l'hymne avant le match", "We sing the anthem before the match", "Tunaibaa wimbo wa taifa kabla ya mechi", "Tunaibaa anthem kabla ya game", null, null, "A2"),
        Phrase("Rendez-vous au terrain à quatre heures", "Meet at the pitch at four", "Tukutane uwanjani saa kumi", null, null, null, "A2")
    ), "u13"),
    Lesson("b-phone", "📱", "Le téléphone", "Phone phrases", "Simu", listOf(
        Phrase("Mon téléphone n'a plus de batterie", "My phone is out of battery", "Simu yangu haina chaji", "Simu yangu haina charge", null, null, "A2"),
        Phrase("Envoie-moi le lien par WhatsApp", "Send me the link on WhatsApp", "Nitumia kiungo kwa WhatsApp", null, null, null, "A2"),
        Phrase("La connexion est très lente ici", "The connection is very slow here", "Mtandao ni polepole hapa", "Net ni slow hapa", null, null, "A2"),
        Phrase("Je te rappelle dans dix minutes", "I'll call you back in ten minutes", "Nitakupigia baada ya dakika kumi", null, null, null, "A2"),
        Phrase("Ton numéro ne passe pas", "Your number doesn't go through", "Nambari yako haipatikani", null, null, null, "B1"),
        Phrase("Recharge-moi mille shillings", "Top me up a thousand shillings", "Niekee vocha ya elfu moja", null, null, null, "A2"),
        Phrase("J'ai reçu ton message vocal", "I got your voice note", "Nimepokea ujumbe wako wa sauti", null, null, null, "A2"),
        Phrase("Mets ton téléphone en silencieux", "Put your phone on silent", "Weka simu kimya", null, null, null, "A2"),
        Phrase("La vidéo s'est coupée deux fois", "The video cut out twice", "Video ilikatika mara mbili", null, null, null, "B1"),
        Phrase("Partage ta connexion, s'il te plaît", "Share your hotspot, please", "Nishirikishe neti, tafadhali", null, null, null, "B1"),
        Phrase("Mon écran est fissuré", "My screen is cracked", "Kioo changu kimepasuka", null, null, null, "B1"),
        Phrase("Le nouveau forfait est moins cher", "The new bundle is cheaper", "Bando mpya ni rahisi", null, null, null, "B1"),
        Phrase("Supprime les vieilles photos", "Delete the old photos", "Futa picha za zamani", null, null, null, "A2"),
        Phrase("La mise à jour prend une heure", "The update takes an hour", "Kuboresha kunachukua saa moja", null, null, null, "B1"),
        Phrase("Ne raccroche pas, j'arrive", "Don't hang up, I'm coming", "Usikate, ninakuja", null, null, null, "A2")
    ), "u13"),
    Lesson("b-health", "🏥", "La santé", "Health phrases", "Afya", listOf(
        Phrase("J'ai mal à la gorge depuis hier", "My throat hurts since yesterday", "Koo linauma tangu jana", null, null, null, "A2"),
        Phrase("Prends deux comprimés après manger", "Take two pills after eating", "Kunywa vidonge viwili baada ya kula", null, null, null, "A2"),
        Phrase("Le dispensaire ouvre à huit heures", "The clinic opens at eight", "Zahanati inafungua saa mbili", null, null, null, "B1"),
        Phrase("Je dois acheter du sirop", "I need to buy syrup", "Ninahitaji kununua sharubati", null, null, null, "A2"),
        Phrase("Tu as l'air fatigué, repose-toi", "You look tired, rest", "Unaonekana umechoka, pumzika", null, null, null, "A2"),
        Phrase("Bois beaucoup d'eau aujourd'hui", "Drink lots of water today", "Kunywa maji mengi leo", null, null, null, "A1"),
        Phrase("La fièvre est tombée ce matin", "The fever broke this morning", "Homa imeshuka asubuhi", null, null, null, "B1"),
        Phrase("Le médecin m'a donné une ordonnance", "The doctor gave me a prescription", "Daktari amenipa cheti cha dawa", null, null, null, "B1"),
        Phrase("Je suis allergique aux arachides", "I'm allergic to peanuts", "Nina aleji ya karanga", null, null, null, "B1"),
        Phrase("Lave-toi les mains avant de manger", "Wash your hands before eating", "Nawa mikono kabla ya kula", null, null, null, "A1"),
        Phrase("J'ai rendez-vous chez le dentiste", "I have a dentist appointment", "Nina miadi kwa daktari wa meno", null, null, null, "B1"),
        Phrase("Ça pique quand j'avale", "It stings when I swallow", "Inauma ninapomeza", null, null, null, "B1"),
        Phrase("Le pharmacien conseille ce remède", "The pharmacist recommends this remedy", "Mfamasia anapendekeza dawa hii", null, null, null, "B1"),
        Phrase("Dors huit heures chaque nuit", "Sleep eight hours nightly", "Lala masaa nane kila usiku", null, null, null, "A1"),
        Phrase("Le palu se soigne vite ici", "Malaria is treated fast here", "Malaria inatibiwa haraka hapa", null, null, null, "B1")
    ), "u13"),
    Lesson("b-food", "🍲", "La cuisine", "Cooking phrases", "Jikoni", listOf(
        Phrase("Fais bouillir l'eau d'abord", "Boil the water first", "Chemsha maji kwanza", null, null, null, "A2"),
        Phrase("Ajoute du sel petit à petit", "Add salt little by little", "Ongeza chumvi kidogo kidogo", null, null, null, "A2"),
        Phrase("Le riz cuit en vingt minutes", "Rice cooks in twenty minutes", "Wali unaiva kwa dakika ishirini", null, null, null, "A2"),
        Phrase("Coupe les oignons en petits morceaux", "Cut onions in small pieces", "Kata vitunguu vipande vidogo", null, null, null, "A2"),
        Phrase("Goûte avant de servir", "Taste before serving", "Onja kabla ya kupakua", null, null, null, "A2"),
        Phrase("Le chapati brûle, retourne-le", "The chapati burns, flip it", "Chapati inaungua, igeuze", null, null, null, "B1"),
        Phrase("Mélange bien la pâte", "Mix the dough well", "Changanya donge vizuri", null, null, null, "A2"),
        Phrase("Sers chaud avec du kachumbari", "Serve hot with kachumbari", "Pakua moto na kachumbari", null, null, null, "B1"),
        Phrase("Il manque du piment", "Chili is missing", "Pilipili inakosekana", null, null, null, "A2"),
        Phrase("Le thé est trop sucré", "The tea is too sweet", "Chai ni tamu sana", null, null, null, "A1"),
        Phrase("Lave les assiettes après manger", "Wash the plates after eating", "Osha vyombo baada ya kula", null, null, null, "A1"),
        Phrase("Le gâteau est au four", "The cake is in the oven", "Keki iko jikoni", null, null, null, "A2"),
        Phrase("Épluche trois pommes de terre", "Peel three potatoes", "Menya viazi vitatu", null, null, null, "A2"),
        Phrase("Le dîner est prêt, venez", "Dinner is ready, come", "Chakula kiko tayari, njoni", null, null, null, "A1"),
        Phrase("Qui veut du rab de pilau ?", "Who wants more pilau?", "Nani anataka pilau zaidi?", null, null, null, "A2")
    ), "u13"),
    Lesson("b-neighbours", "🏘️", "Les voisins", "Neighbourhood phrases", "Mtaani", listOf(
        Phrase("Les voisins font un mariage samedi", "The neighbours hold a wedding Saturday", "Majirani wana harusi Jumamosi", null, null, null, "A2"),
        Phrase("On cotise pour la sécurité", "We contribute for security", "Tunachanga kwa ulinzi", null, null, null, "B1"),
        Phrase("Le robinet commun fuit encore", "The shared tap leaks again", "Bomba la pamoja linavuja tena", null, null, null, "B1"),
        Phrase("Il y a une réunion ce soir", "There's a meeting tonight", "Kuna mkutano leo usiku", null, null, null, "A1"),
        Phrase("Les enfants jouent au ballon dehors", "Kids play ball outside", "Watoto wanacheza mpira nje", null, null, null, "A1"),
        Phrase("Le coq chante à quatre heures", "The rooster crows at four", "Jogoo anawika saa kumi", null, null, null, "A2"),
        Phrase("La boutique ferme à vingt-deux heures", "The shop closes at ten pm", "Duka linafunga saa nne usiku", null, null, null, "B1"),
        Phrase("On nettoie la rue dimanche", "We clean the street Sunday", "Tunasafisha barabara Jumapili", null, null, null, "A2"),
        Phrase("Le pasteur passe demain", "The pastor visits tomorrow", "Mchungaji anapita kesho", null, null, null, "A2"),
        Phrase("Ta chèvre est dans mon jardin", "Your goat is in my garden", "Mbuzi wako yuko bustanini kwangu", null, null, null, "B1"),
        Phrase("Le courant revient à minuit", "Power returns at midnight", "Umeme unarudi usiku wa manane", null, null, null, "B1"),
        Phrase("Les jeunes ont un tournoi", "The youth have a tournament", "Vijana wana mashindano", null, null, null, "A2"),
        Phrase("La mama mboga donne crédit", "The veggie lady gives credit", "Mama mboga anatoa deni", null, null, null, "B1"),
        Phrase("Salut les voisins, bon dimanche", "Hi neighbours, happy Sunday", "Habari majirani, Jumapili njema", null, null, null, "A1"),
        Phrase("On s'entraide comme une famille", "We help each other like family", "Tunasaidiana kama familia", null, null, null, "A2")
    ), "u13")
)