package com.francofun

// Content5: Unit 9 (Prononciation — the missing skill track), Unit 8 KCSE
// drill expansion, Unit 10 (Afrique francophone & opportunity French).
// Additive only, same Lesson/Phrase shape as Content.kt.

// ─── UNIT 9 · PRONONCIATION (u9) ────────────────────────────────────────────

val EXTRA4_LESSONS: List<Lesson> = listOf(
    Lesson("p-nasales", "👃", "Voyelles nasales", "Nasal vowels: an, en, on, in", "Sauti za pua", listOf(
        Phrase("Un bonbon blanc", "A white sweet", "Pip i nyeupe", null, "an/en = [ɑ̃], on = [ɔ̃]. Nose on, mouth open.", "Four nasals: an/en [ɑ̃], on [ɔ̃], in/ain/ein [ɛ̃], un [œ̃]. vent, bon, vin, brun. N before p/b/m stays oral: comme (not nasal).", "A1", true),
        Phrase("Le vent du matin", "The morning wind", "Upepo wa asubuhi", null, "vent: nasal + silent t.", "Final consonants after nasals stay silent: vent, dent, long, rond. Say the nasal, stop — no t/d/g.", "A1"),
        Phrase("Mon nom est Baraka", "My name is Baraka", "Jina langu ni Baraka", "Naitwa Baraka", "mon/nom: [ɔ̃] + silent letters.", "mon, ton, son, nom, bon, maison — the [ɔ̃] family. Self-introduction lives here: Je m'appelle…", "A1", true),
        Phrase("Un vin blanc", "A white wine", "Mvinyo mweupe", null, "in = [ɛ̃]. vin/blanc rhyme pair.", "in/ain/ein/un collapse toward [ɛ̃] in modern speech: vin, pain, plein, brun. Exam oral: distinguish vin [ɛ̃] vs vent [ɑ̃].", "A2"),
        Phrase("Les enfants contents", "Happy children", "Watoto wenye furaha", null, "en → [ɑ̃], ent silent in verb forms.", "ils parlent = il parle in sound. enfants [ɑ̃fɑ̃] — double nasal, great drill word.", "A1"),
        Phrase("Enchanté de te voir", "Nice to meet you", "Nafurahi kukuona", "Poa kukupata", "en- + -é: meeting formula.", "Enchanté(e) — agree with YOUR gender: Enchantée (speaker female). First oral-exam sentence.", "A1"),
        Phrase("Un printemps à Paris", "A spring in Paris", "Majira ya kuchipua Paris", null, "in + temps: nasal cluster drill.", "printemps [pʁɛ̃tɑ̃]: two nasals back to back. Slow it down: prin-temps, then fuse.", "A2"),
        Phrase("Ils sont blonds et contents", "They're blond and happy (m pl)", "Wana nywele za dhahabu na furaha", null, "Agreement silent after nasals too.", "blond/blonde, content/contente: spelling shows gender, sound hides it. Write carefully, speak freely.", "A2"),
        Phrase("Chaque matin, du pain", "Every morning, bread", "Kila asubuhi, mkate", null, "ch + nasal + -ain: combo drill.", "chaque [ʃak], matin [matɛ̃], pain [pɛ̃]. Morning routine = nasal routine.", "A1"),
        Phrase("Bienvenue en France", "Welcome to France", "Karibu Ufaransa", null, "en + country (feminine): en France.", "en France, en Tanzanie, au Kenya, aux USA. Country prepositions ride on gender — drill with nasals.", "A1")
    ), "u9"),
    Lesson("p-r", "🦁", "Le R français", "The French R + guttural drills", "R ya Kifaransa", listOf(
        Phrase("Rouge, rose, rue", "Red, pink, street", "Nyekundu, waridi, barabara", null, "R = throat gargle, not tongue trill.", "French R [ʁ]: uvular, back of throat. Swahili R is trilled — unlearn it. Gargle water, then add vowels: ra, re, ri.", "A1", true),
        Phrase("Merci pour la rue", "Thanks for the street (directions)", "Asante kwa barabara", null, "r + vowel + r: the sandwich drill.", "rue [ʁy], rouge [ʁuʒ], rare [ʁaʁ]. Street French is R French — directions practice doubles as R drill.", "A1"),
        Phrase("Le professeur arrive", "The teacher arrives", "Mwalimu anakuja", null, "-eur ending: R bookends.", "professeur, docteur, acteur: final -r silent-ish but colours the vowel. Don't roll it, breathe it.", "A1"),
        Phrase("Trois frères et sœurs", "Three brothers and sisters", "Ndugu watatu", null, "tr-/fr- clusters: R after consonant.", "trois, frère, prendre, propre. Consonant + R stays tight: one syllable push, no extra vowel (not 'tirois').", "A2"),
        Phrase("Le marché noir", "The black market", "Soko la magendo", null, "r + ch: throat + palate combo.", "marché, chercher, art, porte. R before consonants softens — almost a breath: porte [pɔʁt].", "A2"),
        Phrase("Rira bien qui rira", "He who laughs last (proverb)", "Anayecheka mwisho", null, "R alliteration drill + proverb.", "Rira bien qui rira le dernier. Proverb + R workout. Exam oral: one proverb = cultural marks.", "B1"),
        Phrase("La guerre et la paix", "War and peace", "Vita na amani", null, "-erre endings: guerre, terre, pierre.", "guerre, terre, verre, pierre: R-coloured è. Vocabulary of history topics rides on R.", "B1"),
        Phrase("Regarde le renard", "Look at the fox", "Angalia mbweha", null, "r- initial + -ard: story drill.", "renard, regard, retard, record. Le Renard et le Corbeau (La Fontaine) — read it aloud for R stamina.", "A2"),
        Phrase("Quatre heures et quart", "Quarter past four", "Saa kumi na robo", null, "quatre: R + silent -re ending.", "quatre [katʁ], heure [œʁ]. Time-telling is an R obstacle course — drill it.", "A1"),
        Phrase("Bonjour, je suis Ravi", "Hello, I'm Ravi", "Habari, naitwa Ravi", null, "Introducing with R names.", "Names with R: Ramadhan, Rukia, Raphaël. Own your R — say your name French-style first.", "A1")
    ), "u9"),
    Lesson("p-uou", "👄", "u ou, ou, é è", "Vowel traps: u/ou, é/è", "Vokali hatari", listOf(
        Phrase("Tu as tout lu", "You read everything", "Umesoma kila kitu", null, "tu [ty] vs tout [tu]: lips tight vs round.", "u [y]: lips pushed tight (tu, rue, plus). ou [u]: lips round (tout, vous, jour). Minimal pair #1 — examiners test it.", "A1", true),
        Phrase("Où est le bus ?", "Where is the bus?", "Basi iko wapi?", "Bus iko wapi?", "où [u] vs ou (or): accent = sound + meaning.", "ou [u] (or) vs où [u] (where) sound alike — spelling separates them. ou…ou = either…or.", "A1"),
        Phrase("Du jus de fruit", "Some fruit juice", "Juisi ya matunda", null, "u + jus: tight-lip chain.", "jus, plus, du, dessus. Drill: tu bois du jus — three [y] in a row.", "A1"),
        Phrase("Vous écoutez tout", "You listen to everything", "Munasikiliza kila kitu", null, "ou-chain: vous, écoutez, tout.", "vous [vu], écouter [ekute], tout [tu]. Round-lip chain vs tu [ty] — alternate: tu écoutes tout.", "A2"),
        Phrase("Café ou thé : thé !", "Coffee or tea: tea!", "Kahawa au chai: chai!", null, "é [e] closed vs è [ɛ] open.", "café [kafe] (smile sound) vs lait [lɛ] (relaxed). BÉBÉ vs BELLE — minimal pair #2.", "A1"),
        Phrase("Le père et la mère", "Father and mother", "Baba na mama", null, "è [ɛ]: père, mère, frère.", "è always [ɛ]: père, mère, frère, élève. é usually [e]: école, examen, métro. Accent predicts sound.", "A1"),
        Phrase("J'ai acheté du lait", "I bought milk", "Nimenunua maziwa", null, "ai + lait: [ɛ] contexts.", "ai = [ɛ] in lait, mais, fait (verb 'does'), but [e] in future -ai endings (je parlerai). Position decides.", "A2"),
        Phrase("Les œufs et le bœuf", "Eggs and beef", "Mayai na nyama", null, "œu: [ø] closed vs [œ] open.", "les œufs [ø] (closed, plural) vs un œuf [œf] (open, singular + f!). bœuf [bœf] keeps its f. Glorious trap.", "B1"),
        Phrase("Deux sœurs et un neveu", "Two sisters and a nephew", "Dada wawili na mpwa", null, "eu [ø]: deux, neveu, bleu.", "eu closed [ø]: deux, bleu, neveu. eu open [œ]: neuf (nine), seul? no — seul [sœl] open. sœur [sœʁ] open.", "A2"),
        Phrase("Dessus, dessous, dehors", "On top, below, outside", "Juu, chini, nje", null, "e + double consonant = [ɛ].", "dessus, dessous, mettre, terre: e before double consonants sounds [ɛ]. Spelling rule with sound payoff.", "B1")
    ), "u9"),
    Lesson("p-liaisons", "🔗", "Liaisons", "Linking words in speech", "Kuunganisha maneno", listOf(
        Phrase("Les‿amis arrivent", "Friends arrive", "Marafiki wanakuja", "Mabeshte wanakam", "les‿amis: MANDATORY liaison [z].", "Obligatory: article/adjective + noun (les‿amis, deux‿enfants, grand‿homme). Never skip — skipping marks you instantly.", "A2", true),
        Phrase("Nous‿avons faim", "We're hungry", "Tuna njaa", "Tuna njaa", "nous‿avons: pronoun + verb [z].", "Pronoun liaisons mandatory: nous‿avons, vous‿êtes, ils‿ont. On‿a [n]. ils‿ont [z].", "A2"),
        Phrase("C'est‿un examen", "It's an exam", "Ni mtihani", null, "c'est‿un: [t] link.", "c'est‿un, tout‿un, comment‿allez-vous: [t] liaisons. est‿un vs et un — sound separates verb from 'and'.", "A2"),
        Phrase("Pas‿à pas", "Step by step", "Hatua kwa hatua", "Step by step", "pas‿à: [z] in fixed phrases.", "Fixed-expression liaisons: pas‿à‿pas, de temps‿en temps, petit‿à‿petit. Frozen with their links.", "B1"),
        Phrase("Trop‿important", "Too important", "Muhimu sana", null, "Short adverbs link forward.", "très‿important, trop‿absent, bien‿assez. Adverb + adjective = link. Long adverbs don't: lentement‿arrivé (no).", "B1"),
        Phrase("Ils sont‿allés", "They went", "Walikwenda", null, "être + participle: link the auxiliary.", "ils sont‿allés, nous sommes‿partis. Verb-chain liaisons: auxiliary + participle always linked.", "A2"),
        Phrase("Un long‿été", "A long summer", "Kiangazi kirefu", null, "long‿été: [g] link, rare sound.", "long‿été, sang‿impur: [g] liaisons. Rare — when you nail one, examiners notice.", "B1"),
        Phrase("Et // alors ?", "So?", "Na // basi?", null, "et NEVER liaises. Hard stop.", "Forbidden: et‿ami (wrong!), chez‿eux (wrong in formal). et is a wall — pause, don't link.", "B1"),
        Phrase("Comment‿allez-vous ?", "How are you? (formal)", "Hujambo?", null, "The full greeting chain.", "Comment‿allez-vous [t-v-z]: two links. Full formal greeting = liaison showcase. Drill until smooth.", "A1"),
        Phrase("Bonne‿année !", "Happy New Year!", "Heri ya mwaka mpya!", null, "Festival liaisons: bonne‿année [n].", "bonne‿année, bon‿anniversaire, joyeux‿anniversaire. Celebration phrases carry links — say them linked.", "A1")
    ), "u9"),
    Lesson("p-rythme", "🥁", "Rythme et accent", "Rhythm, stress & intonation", "Mdundo wa Kifaransa", listOf(
        Phrase("Je parle français", "I speak French", "Ninaongea Kifaransa", "Naongea French", "Stress the LAST syllable. Always.", "French stress = final syllable, every rhythmic group: je-PARLE, fran-ÇAIS. No word-stress like English/Swahili.", "A1", true),
        Phrase("Le petit chat est mort", "The little cat is dead (rhythm drill)", "Paka mdogo amekufa", null, "Equal syllables: le-pe-tit-chat-est-mort.", "Syllable-timed: every syllable gets equal time. Clap it: 6 claps, even beats. English squeezes, French marches.", "A2"),
        Phrase("Tu viens ? / Tu viens.", "Coming? / Coming. (intonation pair)", "Unakuja? / Unakuja.", null, "Rise = question, fall = statement.", "Same words, melody decides: rise [↗] questions, fall [↘] answers. Intonation IS grammar in speech.", "A1"),
        Phrase("C'est pas possible !", "That's impossible!", "Haiwezekani!", "Haiwezekani!", "Exclamation: fall + punch the last word.", "Exclamations fall hard: C'est pas POSsible ! Quel IDiot ! Punch final, drop pitch.", "A2"),
        Phrase("Euh… je réfléchis", "Um… I'm thinking", "Eeeh… nafikiria", null, "euh [ø]: the French filler.", "Fillers keep the floor: euh…, ben…, alors…, quoi…. Oral exam: filler + answer beats silence + perfect answer.", "A2"),
        Phrase("Répète après moi : bonjour", "Repeat after me: hello", "Rudia nyuma yangu: hujambo", null, "Shadowing: mimic rhythm, not just words.", "Shadow technique: repeat 1 beat behind audio. Copies melody, speed, liaisons whole. 5 min daily.", "A1"),
        Phrase("Petit à petit", "Little by little", "Kidogo kidogo", "Mora mora", "Even beats + linked: pe-ti-ta-pe-ti.", "petit‿à‿petit: liaisons inside rhythm. Proverb + rhythm + liaison in one breath.", "A2"),
        Phrase("Qu'est-ce que tu fais ce soir ?", "What are you doing tonight?", "Unafanya nini leo?", "Unafanya nini leo?", "Long sentence, ONE stress: soir.", "Rhythmic groups: Qu'est-ce que tu fais | ce soir ? One stress per group, glide inside. Don't stress every word.", "A2"),
        Phrase("Non. Non ! NON !", "No. No! NO!", "Hapana. Hapana! HAPANA!", null, "Volume + pitch = escalation ladder.", "Same word, three volumes: calm, firm, final. Drama drill: play all three. Oral examiners smile.", "A1"),
        Phrase("On y va, doucement", "Let's go, gently", "Twende, polepole", "Twende, polepole", "Two groups, two stresses: VA, MENT.", "On y va | doucement. Comma = breath = new group. Read punctuation as rhythm marks.", "A2")
    ), "u9"),
    Lesson("p-sons", "👂", "Paires minimales", "Sound pairs that change meaning", "Sauti zinazobadilisha maana", listOf(
        Phrase("Tu bois ou tout boit ?", "You drink, or everything drinks?", "Unywi au kila kitu kinakunywa?", null, "tu/tout: [y] vs [u] decides sense.", "tu [ty] vs tout [tu], rue [ʁy] vs roue [ʁu], dessus [dəsy] vs dessous [dəsu]. Pair-drill aloud daily.", "A2", true),
        Phrase("Ces livres ou ses livres ?", "These books or his books?", "Vitabu hivi au vitabu vyake?", null, "ces/ses: [s] vs [s]… identical! Context only.", "ces [se] vs ses [se] sound THE SAME — meaning comes from context. c'est/s'est/sait: same trap, spelling decides.", "B1"),
        Phrase("Le verre est vert", "The glass is green", "Glasi ni kijani", null, "verre/vert/ver: [vɛʁ] triple.", "verre (glass), vert (green), vers (toward), ver (worm): all [vɛʁ]. Context + spelling. Dictation favourite.", "B1"),
        Phrase("Il pleut ou il pleure ?", "Is it raining or is he crying?", "Mvua inanyesha au analia?", null, "pleut [plø] vs pleure [plœʁ]: final R.", "Final -e + R audible: pleure, beurre, heure. Without R: pleut, bleu, deux. Ear training pair.", "A2"),
        Phrase("Un bon bain", "A good bath", "Bafu nzuri", null, "bon [bɔ̃] vs bain [bɛ̃]: two nasals.", "bon/bain, vent/vin, sans/sein: [ɑ̃] vs [ɛ̃]. The nasal contrast examiners test most. Nose + mirror.", "A2"),
        Phrase("La mer est amère", "The sea is bitter", "Bahari ni chungu", null, "mer/amer: [mɛʁ] pair, meaning flips.", "mer (sea), mère (mother), amer (bitter): same sound family. La mère est à la mer — classic sentence.", "B1"),
        Phrase("Poisson ou poison ?", "Fish or poison?", "Samaki au sumu?", null, "-ss- [s] vs -s- [z]: spelling = sound.", "poisson [pwasɔ̃] vs poison [pwazɔ̃], dessert vs désert, poisson vs boisson. Double-s hisses, single-s buzzes.", "B1"),
        Phrase("Il a cent ans sans sang", "He's 100 with no blood (drill)", "Ana miaka 100 bila damu", null, "cent/sans/sang: [sɑ̃] triple.", "cent, sans, sang, sens: all [sɑ̃]. Dictation nightmare, drill delight. Write each 5×.", "B1"),
        Phrase("Cou ou coup ?", "Neck or blow?", "Shingo au pigo?", null, "Final consonant appears then hides.", "cou [ku] vs coup [ku] vs coût [ku] vs couds [ku]: four spellings, one sound. Grammar decides spelling.", "B1"),
        Phrase("Écoute et répète tout", "Listen and repeat everything", "Sikiliza na urudie kila kitu", "Sikiza na urudie kila kitu", "The drill command itself.", "Écoute [ekut], répète [ʁepɛt]: final -e silent, -ent silent. The meta-instruction for all sound work.", "A1")
    ), "u9"),

// ─── UNIT 8 EXTENSION · KCSE DRILLS (u8) ────────────────────────────────────

    Lesson("k-dictee", "✍️", "Dictée", "Dictation training", "Imla", listOf(
        Phrase("Les petits enfants jouent", "The little children play", "Watoto wadogo wanacheza", null, "petits: silent -s. enfants: nasal + silent -ts.", "Dictation rule 1: plural -s/-x NEVER sound. petits [pəti], enfants [ɑ̃fɑ̃]. Write what grammar demands, not what ears catch.", "A2", true),
        Phrase("Ils parlent et elles écoutent", "They (m) speak, they (f) listen", "Wanaongea na wanasikiliza", null, "-ent silent in BOTH verbs.", "parlent = parle in sound. écoutent = écoute. Subject pronoun is your only clue — listen to the START.", "A2"),
        Phrase("J'ai mangé, tu as bu", "I ate, you drank", "Nilikula, ulikunywa", null, "mangé [e] vs bu [y]: participle vowels.", "-é/-er/-ez all [e]: mangé, manger, mangez. Dictation classic: distinguish -é (past) from -er (infinitive) by grammar.", "A2"),
        Phrase("Son père est venu hier", "Her father came yesterday", "Baba yake alikuja jana", null, "venu: nasal + silent -u. hier: [jɛʁ].", "venu, revenue, devenue: -u silent. hier starts with aspired h — no liaison: les // héros, le // hier.", "B1"),
        Phrase("Combien de sœurs as-tu ?", "How many sisters do you have?", "Una dada wangapi?", "Una madem wangapi?", "combien de + noun plural -s silent.", "sœurs [sœʁ]: œu + silent -s. combien, comment, comme: com- always [kɔm].", "A2"),
        Phrase("Il fait très beau aujourd'hui", "The weather's lovely today", "Hali ni nzuri leo", "Hali ni poa leo", "très + beau + aujourd'hui: hui silent.", "aujourd'hui [oʒuʁdɥi]: h and u melt.beau/belle/beaux: [bo] family. Weather dictations are Paper 1 staples.", "A2"),
        Phrase("Nous sommes allés au marché", "We went to the market", "Tulikwenda sokoni", "Tulienda market", "sommes‿allés: [z] liaison + agreement.", "nous sommes‿allés (m) / allées (f). Liaison PROVES the plural — hear [z], write -s.", "B1"),
        Phrase("Elle n'a jamais vu la mer", "She's never seen the sea", "Hajawahi kuiona bahari", null, "jamais/vu/mer: [ɛ] chain + silent r?", "vu [vy], mer [mɛʁ] (R sounds!), jamais [ʒamɛ]. mer R rolls audibly; parler R softens. Ear calibration.", "B1"),
        Phrase("Quel beau cadeau !", "What a lovely gift!", "Zawadi nzuri gani!", null, "quel + beau: exclamation, [k] start.", "quel/quelle/quels/quelles agree in dictation — listen for the noun's gender, write quel to match.", "A2"),
        Phrase("Point final, à la ligne", "Full stop, new line", "Kikomo, mstari mpya", null, "Dictation punctuation is DICTATED: point, virgule, à la ligne.", "Know the meta-words: un point, une virgule, un point d'exclamation, à la ligne, ouvrez les guillemets. Paper 1 survival.", "B1"),
        Phrase("Écoutez bien, je répète une fois", "Listen well, I repeat once", "Sikilizeni, narudia mara moja", null, "Paper 1 plays twice — catch it.", "Deux écoutes: first for gist, second for details. Pen ready before play.", "A2"),
        Phrase("Distinguez -é, -er, -ez", "Distinguish -é, -er, -ez", "Tenganisha -é, -er, -ez", null, "Same sound [e], three spellings.", "mangé (past) vs manger (infinitive) vs mangez (you pl). Grammar decides, not ears.", "B1"),
        Phrase("Le féminin s'entend parfois", "Feminine sometimes sounds", "Uke wakati mwingine unasikika", null, "Concrete: petite, grande, blanche.", "petit/petite, grand/grande, blanc/blanche: audible pairs. vert/verte too. Write what you hear.", "A2"),
        Phrase("Ouvrez les guillemets, fermez-les", "Open quotes, close them", "Fungua nukuu, funga", null, "Dialogue dictation markers.", "« … » : ouvrez/fermez les guillemets. Tiret for speakers: — Bonjour ! dit-il.", "B1"),
        Phrase("Chiffres en lettres", "Numbers in words", "Namba kwa herufi", null, "Dictated numbers write out.", "quatre-vingt-dix, deux cents, mille. Hyphens: dix-sept, vingt-deux. Cent takes s ×200, loses before other numbers.", "B1"),
        Phrase("Relisez pendant la pause", "Re-read during the pause", "Someni tena wakati wa mapumziko", null, "Between playbacks = gold time.", "Check verbs, agreements, accents between listens. Fix one word per pause.", "A2")
    ), "u8"),
    Lesson("k-drills", "⚡", "Drills chronométrés", "Timed grammar sprints", "Mazoezi ya haraka", listOf(
        Phrase("je suis, tu es, il est", "I am, you are, he is", "Mimi ni, wewe ni, yeye ni", null, "Speed conjugation: say all six in 5 seconds.", "être sprint: suis, es, est, sommes, êtes, sont. Then avoir: ai, as, a, avons, avez, ont. Daily 60 seconds.", "A1", true),
        Phrase("je parle, nous parlons", "I speak, we speak", "Ninaongea, tunaongea", null, "Singular vs nous: the -ons jump.", "Every group same jump: parle/parlons, finis/finissons, vends/vendons. Drill the pair, not six forms.", "A1"),
        Phrase("j'ai parlé, je suis allé", "I spoke (avoir), I went (être)", "Niliongea, nilikwenda", null, "Auxiliary choice in under 2 seconds.", "avoir default; être for DR MRS VANDERTRAMP + reflexives. Flash rule: movement/change = être.", "A2"),
        Phrase("le, la, les, un, une, des", "the, a: full article sprint", "Vihusishi vyote", null, "Articles at speed: gender + number.", "Chain drill: le garçon, la fille, les enfants, un examen, une leçon, des stylos. 10 nouns, 30 seconds.", "A1"),
        Phrase("mon, ton, son, notre, votre, leur", "my, your, his, our, your, their", "Vimiliki vyote", null, "Possessives sprint: match the noun.", "mon livre, ma sœur, mes amis, notre école, vos stylos, leurs cahiers. Noun gender decides — fast.", "A2"),
        Phrase("qui, que, dont, où", "who, whom, whose(of), where", "Viunganishi vinne", null, "Relative sprint: function decides.", "qui (does) → que (receives) → dont (de-verb) → où (place/time). Four slots, instant pick.", "B1"),
        Phrase("Il faut que + subjonctif", "Must + subjunctive trigger", "Lazima + hali ya shaka", null, "Trigger sprint: name the mood.", "il faut que, vouloir que, bien que, pour que, avant que → SUBJ. après que, parce que, quand → INDIC. Sort fast.", "B2"),
        Phrase("si + imparfait → conditionnel", "If + past → would", "Kama + wakati → ninge", null, "Condition sprint: match the pair.", "si + présent → futur; si + imparfait → conditionnel; si + plus-que-parfait → conditionnel passé. Three pairs.", "B2"),
        Phrase("hier, aujourd'hui, demain", "Yesterday, today, tomorrow", "Jana, leo, kesho", null, "Time adverb sprint: tense follows.", "hier → passé composé, aujourd'hui → présent/passé, demain → futur. Time word picks the tense before you conjugate.", "A2"),
        Phrase("ne…pas, ne…jamais, ne…plus", "not, never, no longer", "Ukanushi watatu", null, "Negation sprint: wrap at speed.", "ne + verb + pas/jamais/plus/rien/personne/que. Wrap drill: Je ne…pas → swap the second word, keep rhythm.", "A2"),
        Phrase("je parlerai, tu finiras, il vendra", "I will speak, you will finish, he will sell", "Nitaongea, utamaliza, atauza", null, "Future endings identical: -ai/-as/-a.", "One ending set, all verbs. Stems differ (parler-, finir-, vendr-) — drill stems.", "B1"),
        Phrase("j'ai mangé, tu es allé(e)", "I ate, you went", "Nilikula, ulikwenda", null, "Auxiliary pairs at speed.", "avoir default, être for movement. Alternate: mangé/venu, fini/parti, pris/sorti.", "A2"),
        Phrase("le mien, le tien, le sien", "mine, yours, his/hers", "Yangu, yako, yake", null, "Stress pronouns sprint.", "le mien, le tien, le sien, le nôtre, le vôtre, le leur. Takes articles, agrees.", "B1"),
        Phrase("y (là-bas), en (de là)", "y (there), en (of it)", "Huko, humo", null, "Adverbial pronouns sprint.", "J'y vais, j'en veux. y = à+place, en = de+thing/quantity. 5-second rule recall.", "B1"),
        Phrase("plus grand que, moins cher que", "bigger than, cheaper than", "Kubwa kuliko, rahisi kuliko", null, "Comparative frames sprint.", "plus/moins/aussi + adjective + que. le/la/les plus for superlatives.", "B1"),
        Phrase("quel stylo ? quelle règle ?", "which pen? which ruler?", "Kalamu gani? Rula gani?", null, "quel-agreement sprint.", "quel/quelle/quels/quelles in 4 seconds. Noun gender decides.", "A2")
    ), "u8"),
    Lesson("k-images", "🖼️", "Décrire des images", "Picture-description bank", "Kuelezea picha", listOf(
        Phrase("Au centre, un marché animé", "In the middle, a lively market", "Katikati, soko lenye shughuli", null, "Centre-first: anchor the scene.", "Picture formula: Au centre… À gauche… À droite… À l'arrière-plan… Four anchors, then life.", "B1", true),
        Phrase("À gauche, une femme vend des fruits", "Left, a woman sells fruit", "Kushoto, mwanamke anauza matunda", null, "Left anchor + action in present.", "Describe in PRESENT: vend, porte, rit. Actions frozen in the image = present tense, always.", "A2"),
        Phrase("À droite, des enfants jouent", "Right, children play", "Kulia, watoto wanacheza", null, "Right anchor mirrors left.", "Balance left/right for structure marks. Examiners track coverage: did you scan the WHOLE image?", "A2"),
        Phrase("En arrière-plan, des collines", "In the background, hills", "Nyuma, kuna vilima", null, "Background last, atmosphere words.", "Arrière-plan = setting: collines, immeubles, ciel nuageux. Sets mood before your opinion.", "B1"),
        Phrase("Il semble qu'il fasse chaud", "It seems it's hot (+subjunctive!)", "Inaonekana kuna joto", null, "il semble que + SUBJUNCTIVE. Double marks.", "Opinion + grammar flex: Il semble que + subj, Il est évident que + indic. Pair them, explain the difference.", "B2"),
        Phrase("Les couleurs sont vives", "The colours are bright", "Rangi ni nzuri", null, "Colours + agreement drill inside description.", "Les couleurs vives, un ciel bleu, des vêtements rouges. Every colour agrees — free agreement marks.", "A2"),
        Phrase("Cette image me rappelle chez moi", "This picture reminds me of home", "Picha hii inakumbusha nyumbani", null, "Personal link: required closing move.", "Ça me rappelle… / Cela me fait penser à… The personal bridge turns description into communication.", "B1"),
        Phrase("À mon avis, c'est le matin", "In my view, it's morning", "Kwa maoni yangu, ni asubuhi", null, "Deduce + justify: time, season, mood.", "Justify deductions: …car la lumière est douce. …parce que les ombres sont longues. Guess + proof.", "B1"),
        Phrase("On dirait une fête", "It looks like a party", "Inaonekana kama sherehe", null, "on dirait = hedging, very native.", "Hedges: On dirait…, Il paraît que…, Peut-être que…. Confident uncertainty = B2 voice.", "B1"),
        Phrase("Voilà tout ce que je vois", "That's all I see", "Hayo ndiyo yote ninayoyaona", null, "Clean landing line.", "Clôture: Voilà. / C'est tout pour cette image. Then STOP — rambling after the close loses marks.", "A2"),
        Phrase("En haut, le ciel est bleu", "Up top, the sky is blue", "Juu, anga ni bluu", null, "Vertical anchors complete coverage.", "En haut / en bas / au milieu. Top-to-bottom scan proves full coverage.", "A2"),
        Phrase("Au premier plan, il y a un homme", "In the foreground, there's a man", "Mbele, kuna mwanaume", null, "il y a + person for entries.", "Au premier plan, il y a… / on voit… Entry formulas, present tense.", "A2"),
        Phrase("Les gens portent des uniformes", "People wear uniforms", "Watu wamevaa sare", null, "Clothes = easy descriptive marks.", "porter + clothing: un uniforme, une robe rouge. Colours agree — free marks.", "A2"),
        Phrase("Il fait beau sur l'image", "It's sunny in the picture", "Kuna jua kwenye picha", null, "Weather-in-image deduction.", "Il fait beau/gris. Justifiez: …car on voit des ombres courtes. Guess + proof.", "A2"),
        Phrase("L'ambiance est joyeuse", "The mood is cheerful", "Hali ni ya furaha", null, "Ambiance word closes description.", "L'ambiance est… + adjective: joyeuse, tendue, calme. Bridge to opinion.", "B1"),
        Phrase("Je vois deux femmes qui rient", "I see two women laughing", "Ninaona wanawake wawili wanaocheka", null, "qui-clause inside description.", "Noun + qui + verb: des enfants qui jouent. Relative clauses earn B1 marks.", "B1")
    ), "u8"),
    Lesson("k-revision", "🏁", "Révision finale", "Exam-eve checklist", "Marudio ya mwisho", listOf(
        Phrase("Mes fiches sont prêtes", "My notes are ready", "Kalamu zangu ziko tayari", null, "fiches = revision cards. Make them.", "Fiche method: one rule + one example + one trap per card. 20 cards cover 80% of Paper 2.", "A2", true),
        Phrase("J'ai dormi huit heures", "I slept eight hours", "Nililala masaa nane", "Nililala eight hours", "Sleep beats cramming. Past participle agrees? No — dormir takes avoir, no agreement.", "Dormir → dormi (no agreement with avoir, no preceding object). La veille: stop at 9pm, sleep, win.", "A2"),
        Phrase("Deux stylos bleus et une règle", "Two blue pens and a ruler", "Kalamu mbili za buluu na rula", null, "Pack the kit: stylo, règle, gomme.", "Kit list: 2 stylos, crayon, gomme, règle, carte d'identité. No borrowing, no panic.", "A1"),
        Phrase("Je relis chaque réponse", "I re-read every answer", "Ninasoma tena kila jibu", null, "Re-reading catches agreement slips.", "Relecture pass: verbs → subjects, adjectives → nouns, participles → auxiliaries. 5 minutes, +10%.", "B1"),
        Phrase("Le stress est normal", "Stress is normal", "Wasiwasi ni kawaida", "Stress ni normal", "Name it, breathe, begin.", "3-3-3 breathing: 3s in, 3s hold, 3s out. First answer easy on purpose — momentum matters.", "A2"),
        Phrase("J'ai fait de mon mieux", "I did my best", "Nimefanya bidii", "Nimejitoa best", "faire DE son mieux: de, not le.", "faire de son mieux / faire attention à / faire partie de. faire + preposition drills pay off.", "B1"),
        Phrase("Quelle que soit la question", "Whatever the question", "Swali lolote liwe", null, "quel que soit + subjunctive. Ultimate flex.", "quel que + subjunctive: Quelle que soit la difficulté… Memorize one, deploy in essay intro or conclusion.", "B2"),
        Phrase("En avant, sans peur", "Forward, without fear", "Mbele, bila hofu", null, "Exam-morning motto.", "Rituel du jour J: arrive 30 min early, warm up French aloud (order chai in French, in your head).", "A2"),
        Phrase("Après l'examen, on fête", "After the exam, we celebrate", "Baada ya mtihani, tunasherehekea", "Baada ya exam, tunasherehekea", "Future reward sharpens focus.", "après + noun; après que + INDICATIVE (future perfect for flair: après que j'aurai fini, on fêtera).", "B1"),
        Phrase("Bonne chance à tous", "Good luck everyone", "Kila la heri wote", "Good luck wote", "Say it. Mean it. Then deliver.", "Final fiche: lis les questions, justifie tout, vérifie les accords, ne laisse rien de vide. Go.", "A1"),
        Phrase("J'arrive trente minutes avant", "I arrive thirty minutes early", "Ninafika dakika thelathini mapema", null, "Early = calm = marks.", "Locate the room, visit the toilet, breathe. Late arrival loses the first 10 minutes mentally.", "A1"),
        Phrase("N'oublie pas ta carte d'identité", "Don't forget your ID", "Usisahau kitambulisho", null, "No ID, no entry.", "Pièce d'identité + convocation + kit. Checklist the night before, by the door.", "A1"),
        Phrase("J'ai bien révisé, je suis prêt", "I revised well, I'm ready", "Nimejisomea vizuri, niko tayari", "Nimerevise poa, niko ready", "Self-belief script, exam morning.", "Say it aloud: preparation + sleep + method. Confidence is a strategy.", "A2"),
        Phrase("Que Dieu me guide", "May God guide me", "Mungu uniongoze", null, "Faith calms nerves.", "A quiet prayer, then the paper. Whatever your faith — calm is universal.", "A1"),
        Phrase("Un problème à la fois", "One problem at a time", "Tatizo moja kwa wakati", null, "Sequence beats panic.", "Question order is your choice (unless told). Easy first, hard with fresh eyes later.", "A2"),
        Phrase("Je rendrai ma copie fièrement", "I'll hand in my paper proudly", "Nitarejesha karatasi yangu kwa fahari", null, "Finish strong: future tense promise.", "rendre (to hand back) + fièrement. Last line of prep, first line of victory.", "B1")
    ), "u8"),

// ─── UNIT 10 · AFRIQUE FRANCOPHONE (u10) ────────────────────────────────────
// French that pays: the DRC next door, West Africa, Rwanda next door,
// plus work, study and travel French for real opportunities.

    Lesson("f-rdc", "🇨🇩", "La RDC voisine", "French next door: Congo", "Kongo jirani", listOf(
        Phrase("Kinshasa est immense", "Kinshasa is huge", "Kinshasa ni kubwa sana", null, "15M neighbours, one border away.", "La RDC: 100M habitants, 4 langues nationales (lingala, swahili, kikongo, tshiluba), le français officiel. Your closest francophonie.", "A2", true),
        Phrase("Le lingala et le swahili", "Lingala and Swahili", "Kilingala na Kiswahili", null, "Congo speaks YOUR Swahili too.", "Le swahili de Goma/Bukavu ≈ Kenyan Swahili. French + Swahili = hireable across the border.", "A2"),
        Phrase("Le commerce transfrontalier", "Cross-border trade", "Biashara ya mpakani", null, "Busia–Goma trade runs in French.", "Business French: la facture, le devis, la livraison, payer en dollars. Trade vocabulary = income vocabulary.", "B1"),
        Phrase("La rumba congolaise", "Congolese rumba", "Rumba ya Kongo", null, "Franco, Tabu Ley, Fally: French lyrics.", "Music bridge: rumba lyrics mix French + lingala. Listen, catch the French, learn twice as fast.", "A2"),
        Phrase("Un visa pour Goma", "A visa for Goma", "Visa ya kwenda Goma", null, "Border French: documents, stamps, fees.", "Frontière: le visa, le tampon, les frais, la douane. Crossing in French = respect + speed.", "B1"),
        Phrase("Le coltan et le cobalt", "Coltan and cobalt", "Coltan na cobalt", null, "Mining French: the region's economy.", "Mines: le coltan, le cobalt, la concession, l'exportation. Read one French mining article = B2 reading drill.", "B1"),
        Phrase("Nairobi–Kinshasa en avion", "Nairobi–Kinshasa by plane", "Nairobi–Kinshasa kwa ndege", null, "Direct flight, direct opportunity.", "Kenya Airways flies it. L'aéroport, l'embarquement, la correspondance: travel French with a destination.", "A2"),
        Phrase("Travailler à Lubumbashi", "Working in Lubumbashi", "Kufanya kazi Lubumbashi", null, "Jobs: mining, NGOs, logistics.", "Offres d'emploi: postuler, le CV, l'entretien, le contrat. Congolese recruiters write in French.", "B1"),
        Phrase("Le fleuve Congo", "The Congo River", "Mto Kongo", null, "Geography French: fleuve vs rivière.", "un fleuve (reaches the sea) vs une rivière (joins a river). Le fleuve Congo, deuxième débit mondial.", "B1"),
        Phrase("Bienvenue chez nous", "Welcome to our place", "Karibu kwetu", null, "Hospitality phrase, both directions.", "Congolese welcome: Karibu/Koyamba. Offer back: Bienvenue à Nairobi ! Reciprocity in two languages.", "A1")
    ), "u10", culture = "The DRC is Kenya's giant francophone neighbour: Swahili on the street, French in the office. A Kenyan who speaks both is employable from Goma to Lubumbashi."),
    Lesson("f-ouest", "🌍", "Afrique de l'Ouest", "Senegal, Ivory Coast & beyond", "Afrika Magharibi", listOf(
        Phrase("Dakar, ville de la Teranga", "Dakar, city of Teranga (hospitality)", "Dakar, mji wa ukarimu", null, "Teranga: Wolof hospitality, French word.", "Le Sénégal: Dakar, le wolof, le franc CFA, la Teranga. French + hospitality culture = same values as Kenya.", "A2", true),
        Phrase("Abidjan, capitale économique", "Abidjan, economic capital", "Abidjan, mji mkuu wa kiuchumi", null, "Ivorian French is famously lively.", "La Côte d'Ivoire: Abidjan, Yamoussoukro, le cacao (world #1), le nouchi (Ivorian slang — their Sheng!).", "B1"),
        Phrase("Le franc CFA", "The CFA franc", "Faranga ya CFA", null, "One currency, 14 countries.", "Le franc CFA (XOF/XAF): fixed to the euro. Money French: le taux, convertir, le billet. Compare with M-Pesa culture.", "B1"),
        Phrase("Le thiéboudienne du vendredi", "Friday thiéboudienne (fish rice)", "Wali wa samaki wa Ijumaa", null, "National dish, French name.", "La Teranga plate: thiéboudienne (Senegal), attiéké (CI). Food vocabulary carries culture: le poisson braisé.", "A2"),
        Phrase("L'AES et la CEDEAO", "AES and ECOWAS (regional blocs)", "AES na ECOWAS", null, "News French: follow African politics.", "La CEDEAO, l'AES (Mali–Burkina–Niger), l'UA. Reading Jeune Afrique headlines = B2 current-affairs drill.", "B2"),
        Phrase("Étudier à Dakar", "Studying in Dakar", "Kusoma Dakar", null, "UCAD: top francophone university.", "L'UCAD (Dakar), Cocody (Abidjan): scholarships, la bourse, le campus, la résidence. Real destinations.", "B1"),
        Phrase("Le coupé-décalé fait danser", "Coupé-décalé makes people dance", "Coupé-décalé inachezesha", null, "Ivorian sound, French lyrics.", "Le coupé-décalé, le mbalax (Senegal), l'afrobeats connection. Dance floors teach liaison and rhythm.", "A2"),
        Phrase("Un stage à Abidjan", "An internship in Abidjan", "Mafunzo Abidjan", null, "Internship French: stage, convention, tuteur.", "Postuler pour un stage: la lettre de motivation, la convention, le tuteur. Same format as k-lettre, new city.", "B1"),
        Phrase("Le français ivoirien est vivant", "Ivorian French is vibrant", "Kifaransa cha Ivory Coast ni hai", null, "Nouchi: slang like Sheng, fully legit.", "Le nouchi ≈ Sheng: urban, young, mixed. Lesson: French lives in the street, not just books. Speak it alive.", "B1"),
        Phrase("De Nairobi à Dakar", "From Nairobi to Dakar", "Kutoka Nairobi hadi Dakar", null, "Kenya Airways connects them.", "Routes: Nairobi–Dakar via… L'escale, le décalage horaire, le visa. Pan-African mobility in French.", "A2")
    ), "u10"),
    Lesson("f-rwanda", "🇷🇼", "Le Rwanda voisin", "Rwanda: French past, English now", "Rwanda jirani", listOf(
        Phrase("Kigali est très propre", "Kigali is very clean", "Kigali ni safi sana", "Kigali ni safi sana", "The famous cleanliness, in French.", "Le Rwanda: Kigali, le kinyarwanda, l'anglais officiel depuis 2008, le français encore parlé. Umuganda = community work.", "A2", true),
        Phrase("Le français reste utile", "French remains useful", "Kifaransa bado ni muhimu", null, "Older Rwandans + region = French.", "French survives: older generation, Catholic church, DRC trade, OIF membership. Trilingual edge pays.", "B1"),
        Phrase("Bus de Nairobi à Kigali", "Nairobi–Kigali bus", "Basi Nairobi–Kigali", "Bus Nairobi–Kigali", "Night bus, border French at Gatuna.", "La frontière Gatuna/Katuna: le passeport, le laissez-passer EAC, le contrôle. EAC ID works — in French too.", "A2"),
        Phrase("Le génocide : ne jamais oublier", "The genocide: never forget", "Mauaji ya kimbari: tusisahau", null, "Kwibuka: remembrance vocabulary, handled solemnly.", "Le Mémorial de Kigali, Kwibuka (se souvenir), la réconciliation. Solemn register: se recueillir, rendre hommage.", "B2"),
        Phrase("L'EAC parle deux langues", "The EAC speaks two languages", "EAC inaongea lugha mbili", null, "English + French: the bloc's reality.", "La CAE: English official, French working with DRC + Burundi. Meetings, communiqués, trade — both.", "B1"),
        Phrase("Le café rwandais", "Rwandan coffee", "Kahawa ya Rwanda", null, "Coffee French: export, cupping, cooperatives.", "Le café: la coopérative, la récolte, l'exportation. Rwanda's hills = vocabulary of quality.", "A2"),
        Phrase("Visiter les gorilles", "Visiting the gorillas", "Kutembelea sokwe", null, "Tourism French: permits, guides, park rules.", "Les Volcans: le permis, le guide, le briefing. Tourism = French + English + Kinyarwanda, all paying.", "B1"),
        Phrase("Kigali, ville des mille collines", "Kigali, city of a thousand hills", "Kigali, mji wa vilima elfu", null, "Le pays des mille collines.", "Surnom du Rwanda. Descriptions: vallonné, verdoyant, propre, sûr. Adjective agreement in action.", "A2"),
        Phrase("On paie en francs rwandais", "We pay in Rwandan francs", "Tunalipa kwa faranga za Rwanda", null, "Money: le franc rwandais (RWF).", "Compare: franc CFA vs franc rwandais vs shilling. Forex French: le change, le taux du jour.", "A2"),
        Phrase("Murakaza neza !", "Welcome! (Kinyarwanda)", "Karibu! (Kinyarwanda)", null, "One Kinyarwanda word opens doors.", "Murakaza neza = Bienvenue. Like Sheng at home: one local word proves respect. Then continue in French.", "A1")
    ), "u10"),
    Lesson("f-travail", "💼", "Français pro", "Work French: CV to meeting", "Kifaransa cha kazi", listOf(
        Phrase("Ci-joint mon CV", "Attached is my CV", "Nimeambatanisha CV yangu", null, "Application email, one line.", "Email pro: Objet: Candidature — [poste]. Ci-joint mon CV et ma lettre. Cordialement + full name + phone.", "B1", true),
        Phrase("Je parle trois langues", "I speak three languages", "Ninaongea lugha tatu", "Naongea lugha tatu", "Trilingual = the pitch.", "CV line: Trilingue anglais–swahili–français (niveau B2). Put it TOP of the CV, bold.", "A2"),
        Phrase("L'entretien est jeudi", "The interview is Thursday", "Mahojiano ni Alhamisi", "Interview ni Thursday", "entretien = interview (job).", "Préparer: renseignez-vous sur l'entreprise, préparez 3 questions, dormez tôt. Present, ponctuel, souriant.", "B1"),
        Phrase("Parlez-moi de vous", "Tell me about yourself", "Jieleze", null, "The opener: 90 seconds, past→present→future.", "Structure: formation (passé) → expérience (présent) → projet (futur). Three tenses, one answer.", "B1"),
        Phrase("Quels sont vos points forts ?", "What are your strengths?", "Ni nini nguvu zako?", null, "Strengths with PROOF, not adjectives.", "Je suis rigoureux : + example. Ponctuel, autonome, bilingue — each with one concrete proof.", "B1"),
        Phrase("La réunion commence à neuf heures", "The meeting starts at nine", "Mkutano unaanza saa tatu", null, "Meeting French: ordre du jour, PV.", "La réunion: l'ordre du jour, le compte-rendu (PV), prendre la parole, lever la séance.", "B1"),
        Phrase("Je vous envoie le devis", "I'll send you the quote", "Nitakutumia makadirio", null, "devis/facture: trade pair.", "le devis (before) → la facture (after) → le reçu (proof). Freelancer French in three nouns.", "B1"),
        Phrase("Cordialement, Baraka", "Best regards, Baraka", "Wako, Baraka", null, "Email sign-off ladder.", "Bises (friends) → Cordialement (standard pro) → Salutations distinguées (formal). Never mix.", "A2"),
        Phrase("Je suis disponible de suite", "I'm available immediately", "Ninapatikana mara moja", null, "disponible: the magic word.", "Disponible + de suite / dès lundi. Availability closes deals: follow with your number, twice.", "B1"),
        Phrase("On signe quand ?", "When do we sign?", "Tunasaini lini?", null, "Closing: direct, polite, soon.", "le contrat, la période d'essai, le salaire brut/net, les congés. Read every clause — in French.", "B1")
    ), "u10"),
    Lesson("f-etudes", "🎓", "Études en français", "Study abroad in French", "Kusoma kwa Kifaransa", listOf(
        Phrase("Une bourse pour Dakar", "A scholarship for Dakar", "Ufadhili wa kusoma Dakar", "Scholarship ya Dakar", "bourse = scholarship. The golden word.", "La bourse: postuler avant mars, relevés + lettres de recommandation + projet d'études. Start Form 3.", "B1", true),
        Phrase("L'Alliance Française de Nairobi", "Nairobi's Alliance Française", "Alliance Française ya Nairobi", null, "DELF/DALF exams happen here.", "L'Alliance: cours, DELF B2 (university entry in France), médiathèque, events. Your launchpad.", "A2"),
        Phrase("Le DELF B2 ouvre les facs", "DELF B2 opens universities", "DELF B2 inafungua vyuo", null, "B2 certificate = admission ticket.", "DELF B2: compréhension + production, oral + écrit. Score 50/100, no section under 5. This app IS the prep.", "B1"),
        Phrase("Mon projet d'études", "My study plan", "Mpango wangu wa masomo", null, "Campus France asks for it.", "Projet d'études: formation visée + pourquoi la France + débouchés au Kenya. Three paragraphs, future tense.", "B1"),
        Phrase("La résidence universitaire", "University housing", "Hosteli za chuo", null, "CROUS housing: apply early.", "Le CROUS: résidence, resto U, bourse sur critères sociaux. Budget: ~500€/month outside Paris.", "B1"),
        Phrase("Les cours magistraux et les TD", "Lectures and tutorials", "Mihadhara na mafunzo", null, "French uni format: CM + TD + TP.", "CM (cours magistral, 200 students) + TD (group work) + partiels (exams). Different game from KCSE.", "B1"),
        Phrase("Je veux faire médecine", "I want to study medicine", "Nataka kusoma udaktari", null, "faire + field = study it.", "faire médecine/droit/commerce. PASS/LAS for medicine (selective!). Sciences Po for politics. Know the tracks.", "A2"),
        Phrase("Le visa étudiant", "The student visa", "Visa ya mwanafunzi", null, "Paperwork French: dossier, justificatifs.", "Dossier: admission + fonds (615€/mois) + logement + assurance. Campus France interview IN FRENCH — oral exam prep pays.", "B1"),
        Phrase("Parler couramment en un an", "Speaking fluently in a year", "Kuongea fasaha kwa mwaka", null, "Immersion math: 1 year ≈ B2.", "Immersion: cours + job étudiant + coloc francophone. No English bubble. 20h/semaine = B2 in 12 months.", "A2"),
        Phrase("De retour pour construire le Kenya", "Back to build Kenya", "Kurudi kuijenga Kenya", null, "Return narrative wins scholarships.", "Juries fund futures: …pour revenir + project. Brain gain framing: Je reviendrai… + infinitive.", "B1")
    ), "u10"),
    Lesson("f-voyage", "✈️", "Voyager en Afrique", "Travel French across Africa", "Kusafiri Afrika", listOf(
        Phrase("Un aller-retour pour Douala", "Return ticket to Douala", "Tiketi ya kwenda na kurudi Douala", null, "aller-retour saves money and French.", "Billet: aller simple vs aller-retour, classe éco, escale. Douala, Abidjan, Dakar — same counter French.", "A2", true),
        Phrase("L'hôtel est-il près du centre ?", "Is the hotel near downtown?", "Hoteli iko karibu na mjini?", null, "est-il: inversion sounds right here.", "Hotel checklist: C'est combien la nuit ? Le petit-déjeuner est inclus ? Il y a le wifi ? Check-in French.", "B1"),
        Phrase("Je suis Kenyan, et vous ?", "I'm Kenyan, and you?", "Mimi ni Mkenya, na wewe?", "Mimi ni Mkenya, na wewe?", "Nationality swap opens conversations.", "Je suis Kenyan(e). Et vous, vous venez d'où ? Nationalities: Sénégalais, Ivoirien, Congolais, Rwandais.", "A1"),
        Phrase("C'est ma première fois ici", "It's my first time here", "Hii ni mara yangu ya kwanza hapa", null, "First-time magic: locals adopt you.", "Première fois + où + question: C'est ma première fois à Dakar, que dois-je voir ? Instant guides.", "A2"),
        Phrase("Quel plat local conseillez-vous ?", "Which local dish do you recommend?", "Chakula gani cha kienyeji unapendekeza?", null, "Food question unlocks culture.", "Plat local: thiéboudienne, attiéké, pondu, brochettes. Goûter = taste: Puis-je goûter ? Markets first.", "B1"),
        Phrase("Prenez-moi en photo, s'il vous plaît", "Take my photo, please", "Nipige picha, tafadhali", "Nipige picha tafadhali", "Photo French: polite + clear.", "Prenez-moi/nous en photo. On peut ? (permission). Puis: Merci, c'est gentil ! Souvenirs secured.", "A2"),
        Phrase("Où sont les toilettes ?", "Where's the bathroom?", "Choo kiko wapi?", "Choo iko wapi?", "Survival question, zero shame.", "Où sont…? + les toilettes/la sortie/le taxi. Asked 10× daily — own it.", "A1"),
        Phrase("L'addition, on partage", "The bill — let's split", "Bill, tunagawana", "Bill, tunasplit", "on partage: friendship preserved.", "Chacun paie sa part / C'est moi qui invite (my treat) / On partage. Money talk, French style.", "A2"),
        Phrase("J'ai raté ma correspondance", "I missed my connection", "Nimekosa ndege ya kuunganisha", null, "correspondance = connection (flight).", "Airport rescue: J'ai raté… / Mon vol est annulé. Je cherche le comptoir… + airline name. Stay calm, stay French.", "B1"),
        Phrase("Merci pour l'accueil chaleureux", "Thanks for the warm welcome", "Asante kwa ukarimu", null, "Farewell line that gets invitations back.", "L'accueil chaleureux, l'hospitalité, la générosité. Thank specifically, be invited specifically.", "B1")
    ), "u10")
)
