package com.francofun

// §4: Units 1–6 expansion. Levels per §4.2 (A1/A2/B1); ~10% of phrases tagged core.

private fun P2(fr: String, en: String, sw: String, sheng: String? = null, tip: String? = null, grammar: String? = null, level: String = "A1", core: Boolean = false) =
    Phrase(fr, en, sw, sheng, tip, grammar, level, core)

val EXTRA_LESSONS: List<Lesson> = listOf(
    Lesson("ask", "❓", "Poser des questions", "Asking questions", "Kuuliza maswali", listOf(
        P2("Qui est-ce ?", "Who is it?", "Ni nani?", null, null, null, "A1", true),
        P2("Qu'est-ce que c'est ?", "What is it?", "Ni nini?", null, "Starter kit for every question: qu'est-ce que…", null, "A1", true),
        P2("Où habites-tu ?", "Where do you live?", "Unaishi wapi?", "Unakaa wapi?", null, "Tu-form (friends). With strangers: Où habitez-vous ?"),
        P2("Où vas-tu ?", "Where are you going?", "Unaenda wapi?"),
        P2("Quand est-ce que tu viens ?", "When are you coming?", "Unakuja lini?"),
        P2("À quelle heure ?", "At what time?", "Saa ngapi?", null, null, null, "A1", true),
        P2("Pourquoi ?", "Why?", "Kwa nini?", null, null, null, "A1", true),
        P2("Comment ça marche ?", "How does it work?", "Inafanya kazi vipi?"),
        P2("Combien de temps ?", "How long?", "Kwa muda gani?"),
        P2("C'est à qui ?", "Whose is it?", "Ni ya nani?"),
        P2("Quelle est ton adresse ?", "What's your address?", "Anwani yako ni ipi?"),
        P2("Que fais-tu ?", "What are you doing?", "Unafanya nini?", "Unafanya nini?", null, null, "A1"),
        P2("Tu fais quoi ce soir ?", "What are you up to tonight?", "Unafanya nini leo usiku?"),
        P2("Avec qui ?", "With whom?", "Na nani?"),
        P2("Tu parles français ?", "Do you speak French?", "Unaongea Kifaransa?"),
        P2("C'est quoi ton numéro ?", "What's your number?", "Nambari yako ni ipi?"),
        P2("On se voit où ?", "Where shall we meet?", "Tutaonana wapi?"),
        P2("Tu viens avec moi ?", "Are you coming with me?", "Unakuja nami?"),
        P2("C'est quand ton anniversaire ?", "When is your birthday?", "Siku yako ya kuzaliwa ni lini?"),
        P2("Tu veux quoi ?", "What do you want?", "Unataka nini?"),
        P2("Il est quelle heure ?", "What time is it?", "Ni saa ngapi?", null, null, null, "A1")
    ), "u1", "French has three ways to ask (intonation, est-ce que, inversion) — intonation alone ('Tu viens ?') is the most spoken and the easiest to start with."),
    Lesson("alphabet", "🔤", "L'alphabet", "The alphabet", "Alfabeti", listOf(
        P2("A comme Amélie", "A as in Amélie", "A kama Amélie", null, "Spelling aloud matters for phone calls and forms.", null, "A1", true),
        P2("B comme Bernard", "B as in Bernard", "B kama Bernard"),
        P2("C comme Camille", "C as in Camille", "C kama Camille"),
        P2("Comment ça s'écrit ?", "How is that spelled?", "Inaandikwaje?", null, null, null, "A1", true),
        P2("Ça s'écrit avec un accent", "It's written with an accent", "Inaandikwa na accent"),
        P2("Pouvez-vous épeler ?", "Can you spell it?", "Unaweza kutamka herufi moja moja?"),
        P2("Je vais épeler mon nom", "I'll spell my name", "Nitaandika jina langu herufi kwa herufi"),
        P2("Dis-moi lettre par lettre", "Tell me letter by letter", "Niambie herufi kwa herufi"),
        P2("Mon nom s'écrit K-A-M-A-U", "My name is spelled K-A-M-A-U", "Jina langu linaandikwa K-A-M-A-U", null, "Swap in your own name and practise it aloud."),
        P2("Ça commence par quelle lettre ?", "What letter does it start with?", "Inaanza na herufi gani?"),
        P2("Il y a un trait d'union", "There's a hyphen", "Kuna kistari", null, "Jean-Paul, Marie-Claire — hyphens are everywhere."),
        P2("Une voyelle", "A vowel", "Irabu", null, "A, E, I, O, U (and Y, sometimes)."),
        P2("Une consonne", "A consonant", "Konsonanti"),
        P2("Double consonne", "Double consonant", "Konsonanti maradufu", null, "In 'pomme' you say one long m."),
        P2("L'accent aigu (é)", "The acute accent (é)", "Accent aigu", null, "É sounds like 'ay' — café, étudiant.", null, "A1"),
        P2("L'accent grave (è)", "The grave accent (è)", "Accent grave", null, "È sounds open, like 'eh' — père, mère."),
        P2("L'accent circonflexe (ê)", "The circumflex (ê)", "Accent circonflexe", null, "Often marks a lost s: forêt = forest."),
        P2("L'apostrophe (')", "The apostrophe", "Apostrofi", null, "L'homme, j'ai — French hates vowel collisions."),
        P2("Les accents changent le sens", "Accents change meaning", "Accent hubadilisha maana", null, "Ou (or) vs où (where) — listen for the difference."),
        P2("Écoute et répète", "Listen and repeat", "Sikiliza na rudia", null, null, null, "A1", true),
        P2("Je ne sais pas l'épeler", "I can't spell it", "Sijui kuandika herufi zake"),
        P2("Le clavier français (AZERTY)", "The French keyboard (AZERTY)", "Kibodi ya Kifaransa", null, "A and Q swap places — fun on library computers."),
        P2("Majuscule", "Capital letter", "Herufi kubwa"),
        P2("Minuscule", "Small letter", "Herufi ndogo"),
        P2("Point d'exclamation !", "Exclamation mark!", "Alama ya mshangao")
    ), "u1"),
    Lesson("colours", "🎨", "Couleurs et tailles", "Colours and sizes", "Rangi na ukubwa", listOf(
        P2("Rouge", "Red", "Nyekundu", null, null, "Adjectives agree: rouge/rouge, but most change.", "A1", true),
        P2("Bleu", "Blue", "Bluu", null, null, "Bleu → bleue (f).", "A1", true),
        P2("Vert", "Green", "Kijani", null, null, "Vert → verte (f)."),
        P2("Jaune", "Yellow", "Njano"),
        P2("Noir", "Black", "Nyeusi", null, null, "Noir → noire (f)."),
        P2("Blanc", "White", "Nyeupe", null, null, "Blanc → blanche (f) — the rebel."),
        P2("Gris", "Grey", "Kijivu"),
        P2("Rose", "Pink", "Waridi", "Pinki"),
        P2("Orange", "Orange", "Chungwa", null, "Never changes — invariable, like marron."),
        P2("Marron", "Brown", "Kahawia", null, "Invariable too."),
        P2("Violet", "Purple", "Zambarau", null, null, "Violet → violette (f)."),
        P2("Quelle est ta couleur préférée ?", "What's your favourite colour?", "Rangi unayoipenda ni ipi?"),
        P2("Ma couleur préférée est le bleu", "My favourite colour is blue", "Rangi ninayoipenda ni bluu", null, "Colours used as nouns are masculine: le bleu."),
        P2("C'est de quelle couleur ?", "What colour is it?", "Ni rangi gani?"),
        P2("Grand", "Big", "Kubwa", null, null, "Grand → grande (f).", "A1", true),
        P2("Petit", "Small", "Ndogo", null, null, "Petit → petite (f).", "A1"),
        P2("C'est trop petit", "It's too small", "Ni ndogo sana"),
        P2("C'est trop grand", "It's too big", "Ni kubwa sana"),
        P2("Long", "Long", "Ndefu", null, null, "Long → longue (f)."),
        P2("Court", "Short", "Fupi"),
        P2("Large", "Wide", "Pana"),
        P2("Étroit", "Narrow", "Nyembamba"),
        P2("De la même taille", "The same size", "Ukubwa mmoja"),
        P2("C'est parfait !", "It's perfect!", "Ni kamili!", "Ni fiti!", null, null, "A1"),
        P2("J'aime beaucoup cette couleur", "I really like this colour", "Ninapenda rangi hii sana")
    ), "u2"),
    Lesson("directions", "🧭", "Les directions", "Directions", "Maelekezo", listOf(
        P2("Où est… ?", "Where is…?", "Iko wapi…?", null, null, null, "A1", true),
        P2("Tournez à gauche", "Turn left", "Pinda kushoto"),
        P2("Tournez à droite", "Turn right", "Pinda kulia"),
        P2("Continuez tout droit", "Keep going straight", "Endelea moja kwa moja", null, null, null, "A1"),
        P2("Après le rond-point", "After the roundabout", "Baada ya raundi"),
        P2("Au deuxième feu", "At the second light", "Kwa taa ya pili"),
        P2("Prenez la première rue", "Take the first street", "Ingia barabara ya kwanza"),
        P2("C'est près d'ici", "It's near here", "Iko karibu hapa"),
        P2("C'est loin d'ici", "It's far from here", "Iko mbali hapa"),
        P2("C'est à deux pas", "It's a stone's throw away", "Iko karibu sana", null, "Literally 'two steps'."),
        P2("C'est juste là", "It's right there", "Iko hapo tu"),
        P2("Vous ne pouvez pas le rater", "You can't miss it", "Huwezi kuikosa"),
        P2("Suivez les panneaux", "Follow the signs", "Fuata vibao"),
        P2("Descendez cette rue", "Go down this street", "Shuka barabara hii"),
        P2("Montez la rue", "Go up the street", "Panda barabara hii"),
        P2("Traversez le pont", "Cross the bridge", "Vuka daraja"),
        P2("Devant la banque", "In front of the bank", "Mbele ya benki"),
        P2("Derrière la gare", "Behind the station", "Nyuma ya stesheni"),
        P2("Au bout de la rue", "At the end of the street", "Mwisho wa barabara"),
        P2("À combien de minutes ?", "How many minutes away?", "Ni dakika ngapi?"),
        P2("Pouvez-vous me montrer sur la carte ?", "Can you show me on the map?", "Unaweza kunionyesha kwa ramani?"),
        P2("Je suis perdu", "I'm lost", "Nimepotea", null, "Useful and honest — people love helping.", null, "A1"),
        P2("Revenez en arrière", "Go back", "Rudi nyuma"),
        P2("Vous êtes arrivé", "You've arrived", "Umefika"),
        P2("Merci pour votre aide", "Thanks for your help", "Asante kwa msaada wako")
    ), "u4", culture = "In much of Francophone Africa (Dakar, Abidjan, Kinshasa), asking a stranger for directions often turns into them walking you part of the way — accept graciously and offer a small thanks."),
    Lesson("money", "💰", "Argent et banque", "Money and banking", "Pesa na benki", listOf(
        P2("Je voudrais retirer de l'argent", "I'd like to withdraw money", "Ningependa kutoa pesa", null, null, null, "A2"),
        P2("Où est la banque ?", "Where is the bank?", "Benki iko wapi?"),
        P2("Où est le distributeur ?", "Where is the ATM?", "ATM iko wapi?", "ATM iko wapi?", null, null, "A2"),
        P2("Le guichet est ouvert ?", "Is the counter open?", "Dirisha limefunguliwa?"),
        P2("Les frais sont de combien ?", "How much are the fees?", "Makato ni kiasi gani?"),
        P2("Quel est le taux de change ?", "What's the exchange rate?", "Kiwango cha ubadilishaji ni kipi?"),
        P2("Où changer l'argent ?", "Where to change money?", "Kubadilisha pesa wapi?"),
        P2("Je voudrais changer des shillings", "I'd like to change shillings", "Ningependa kubadilisha shilingi"),
        P2("Le shilling", "The shilling", "Shilingi", null, null, "A1"),
        P2("Le franc CFA", "The CFA franc", "Faranga ya CFA", null, "Used in Dakar, Abidjan and most of Francophone West/Central Africa."),
        P2("Le billet", "The banknote", "Noti"),
        P2("La pièce", "The coin", "Sarafu"),
        P2("Je paie avec mon téléphone", "I'll pay with my phone", "Nitalipa na simu", "Nitalipa na M-Pesa", "Mobile money works across Francophone Africa too — look for Orange Money, MTN, M-Pesa."),
        P2("Payer en espèces", "Pay in cash", "Kulipa taslimu", "Kulipa cash"),
        P2("Payer par carte", "Pay by card", "Kulipa na kadi"),
        P2("J'ai besoin de monnaie", "I need change", "Nahitaji chenchi"),
        P2("Gardez la monnaie", "Keep the change", "Bakia na chenchi"),
        P2("Je n'ai pas assez", "I don't have enough", "Sina za kutosha"),
        P2("Un reçu, s'il vous plaît", "A receipt, please", "Risiti tafadhali"),
        P2("C'est combien au total ?", "How much altogether?", "Jumla ni ngapi?", null, null, null, "A2", true),
        P2("La carte ne marche pas", "The card doesn't work", "Kadi haifanyi kazi"),
        P2("Remboursez-moi", "Refund me", "Nirudishie pesa"),
        P2("Économiser", "To save (money)", "Kuweka akiba"),
        P2("Dépenser", "To spend", "Kutumia pesa"),
        P2("Gagner sa vie", "To earn a living", "Kujipatia kipato", null, null, "B1"),
        P2("La banque ouvre à quelle heure ?", "What time does the bank open?", "Benki inafungua saa ngapi?")
    ), "u4", culture = "Mobile money is everyday life in Nairobi and in Dakar, Abidjan and Kinshasa alike (Orange Money, MTN MoMo, Airtel). Cash is still king in markets — always ask if mobile is accepted before assuming."),
    Lesson("transport", "🚐", "Transports", "Getting around", "Usafiri", listOf(
        P2("Où part ce matatu ?", "Where does this matatu leave from?", "Matatu hii inaenda wapi?", null, "Matatu = Nairobi's shared minibus; say where you're headed first.", null, "A1"),
        P2("Combien le trajet ?", "How much is the ride?", "Nauli ni ngapi?", null, null, null, "A1", true),
        P2("Ça passe par le centre ?", "Does it go through town?", "Inapitia town?", "Inapitia tao?"),
        P2("C'est direct ?", "Is it direct?", "Ni direct?", "Ni direct?"),
        P2("Le chauffeur", "The driver", "Dereva"),
        P2("Le receveur", "The conductor", "Kondakta", "Konda", "The one shouting destinations out the door."),
        P2("Montez vite !", "Get in quick!", "Panda haraka!"),
        P2("Arrêtez-vous ici, s'il vous plaît", "Stop here, please", "Simama hapa tafadhali"),
        P2("Je descends au prochain arrêt", "I'm getting off at the next stop", "Nitashuka kituo kinachofuata"),
        P2("Arrêt suivant ?", "Next stop?", "Kituo kinachofuata?"),
        P2("Terminus ?", "Last stop?", "Mwisho?"),
        P2("Un taxi, s'il vous plaît", "A taxi, please", "Teksi tafadhali"),
        P2("Mettez le compteur", "Put the meter on", "Washa mita"),
        P2("Le boda", "The motorbike taxi", "Boda", "Boda", null, null, "A2"),
        P2("Le tuk-tuk", "The tuk-tuk", "Tuk-tuk"),
        P2("À pied", "On foot", "Kwa miguu", null, null, "A1"),
        P2("À quelle heure part le bus ?", "What time does the bus leave?", "Basi linaondoka saa ngapi?"),
        P2("La gare routière", "The bus station", "Stesheni ya mabasi"),
        P2("C'est complet", "It's full", "Imejaa"),
        P2("Embouteillages !", "Traffic jam!", "Foleni!", "Jam!", null, null, "A2"),
        P2("En retard à cause du trafic", "Late because of traffic", "Nimechelewa kwa sababu ya foleni", null, "The universal Nairobi excuse — works in French too."),
        P2("Conduisez lentement, s'il vous plaît", "Drive slowly, please", "Endesha polepole tafadhali"),
        P2("Tournez ici", "Turn here", "Pinda hapa"),
        P2("Tout droit jusqu'au bout", "Straight to the end", "Moja kwa moja hadi mwisho"),
        P2("Bon trajet !", "Have a good ride!", "Safari njema!", null, null, "A1")
    ), "u4"),
    Lesson("emergencies", "🚨", "Urgences", "Emergencies", "Dharura", listOf(
        P2("Au secours !", "Help!", "Msaada!", null, null, null, "A1", true),
        P2("À l'aide !", "Help me!", "Nisaidie!"),
        P2("Au feu !", "Fire!", "Moto!"),
        P2("Appelez une ambulance", "Call an ambulance", "Pigia ambulensi", null, null, null, "A1"),
        P2("Appelez la police", "Call the police", "Pigia polisi"),
        P2("Appelez un médecin", "Call a doctor", "Mwite daktari"),
        P2("Les pompiers", "The firefighters", "Wazima moto"),
        P2("Le commissariat", "The police station", "Kituo cha polisi"),
        P2("J'ai besoin d'aide", "I need help", "Ninahitaji msaada", null, null, null, "A1", true),
        P2("Mon ami est blessé", "My friend is hurt", "Rafiki yangu ameumia"),
        P2("Elle est inconsciente", "She's unconscious", "Hajitambui"),
        P2("Il saigne", "He's bleeding", "Anatoka damu"),
        P2("Ne bougez pas", "Don't move", "Usisonge"),
        P2("Asseyez-vous", "Sit down", "Keti chini"),
        P2("Respirez lentement", "Breathe slowly", "Pumua polepole"),
        P2("Restez calme", "Stay calm", "Tulia"),
        P2("C'est urgent", "It's urgent", "Ni dharura"),
        P2("J'ai perdu mon passeport", "I've lost my passport", "Nimepoteza pasipoti yangu"),
        P2("J'ai perdu mon téléphone", "I've lost my phone", "Nimepoteza simu yangu"),
        P2("On m'a volé mon sac", "My bag was stolen", "Nimeibiwa mkoba"),
        P2("On a volé ma valise", "My suitcase was stolen", "Nimeibiwa begi"),
        P2("Où porter plainte ?", "Where do I report it?", "Niripoti wapi?"),
        P2("Je suis diabétique", "I'm diabetic", "Nina kisukari"),
        P2("Une allergie grave", "A serious allergy", "Aleji kali"),
        P2("Tout va bien", "Everything is fine", "Kila kitu ni sawa", null, null, "A1"),
        P2("Dieu merci !", "Thank God!", "Mungu ashukuriwe!", "Thank God!")
    ), "u4"),
    Lesson("housing", "🏠", "Se loger", "Housing", "Makazi", listOf(
        P2("Je cherche une chambre", "I'm looking for a room", "Ninatafuta chumba", null, null, null, "A2"),
        P2("Je cherche un appartement", "I'm looking for a flat", "Ninatafuta nyumba"),
        P2("Quel est le loyer ?", "What's the rent?", "Kodi ni kiasi gani?", null, null, null, "A2", true),
        P2("Le loyer par mois", "The monthly rent", "Kodi kwa mwezi"),
        P2("La caution", "The deposit", "Dipoziti", null, "Usually one month's rent, same as Nairobi."),
        P2("Le contrat", "The contract", "Mkataba"),
        P2("Signer le bail", "Sign the lease", "Saini mkataba"),
        P2("L'eau et l'électricité sont comprises ?", "Are water and electricity included?", "Maji na stima zimejumuishwa?"),
        P2("L'eau chaude", "Hot water", "Maji ya moto"),
        P2("L'électricité coupe souvent", "Power cuts are frequent", "Stima hukatika mara kwa mara", "Stima inapotea"),
        P2("Le Wi-Fi marche ?", "Does the Wi-Fi work?", "Wi-Fi inafanya kazi?"),
        P2("C'est meublé", "It's furnished", "Imeandaliwa samani"),
        P2("La chambre à coucher", "The bedroom", "Chumba cha kulala"),
        P2("La cuisine", "The kitchen", "Jikoni", null, null, "A1"),
        P2("La salle de bain", "The bathroom", "Bafu"),
        P2("Le salon", "The living room", "Sebule"),
        P2("Le balcon", "The balcony", "Balconi"),
        P2("Quand puis-je visiter ?", "When can I visit?", "Naweza kutembelea lini?"),
        P2("Je prends un mois d'abord", "I'll take one month first", "Nitachukua mwezi mmoja kwanza"),
        P2("Le quartier est calme ?", "Is the neighbourhood quiet?", "Mtaa ni mtulivu?"),
        P2("Le gardien", "The caretaker/guard", "Mlinzi", "Watchman"),
        P2("Les voisins sont sympas", "The neighbours are nice", "Majirani ni wazuri"),
        P2("C'est bruyant la nuit", "It's noisy at night", "Kuna kelele usiku"),
        P2("Déménager", "To move house", "Kuhama"),
        P2("Les cartons", "The moving boxes", "Makaratoni"),
        P2("Bienvenue chez moi !", "Welcome to my place!", "Karibu kwangu!", null, null, "A1"),
        P2("Faites comme chez vous", "Make yourself at home", "Jisikie nyumbani")
    ), "u4"),
    Lesson("friends", "🥳", "Entre amis", "Among friends", "Kwa marafiki", listOf(
        P2("Salut mon pote !", "Hey buddy!", "Niaje beshte!", "Niaje msee!", null, null, "A2"),
        P2("Ça fait un bail !", "Long time!", "Muda mrefu!", "Muda!", "Bail = originally a lease — time you 'hold'."),
        P2("Quoi de neuf mon ami ?", "What's up my friend?", "Kuna nini beshte?", "Kuna nini msee?"),
        P2("Tu viens ce soir ?", "Are you coming tonight?", "Unakuja leo usiku?", null, null, null, "A2", true),
        P2("On sort ce soir ?", "Are we going out tonight?", "Tunatoka leo usiku?"),
        P2("Tu es libre demain ?", "Are you free tomorrow?", "Uko free kesho?", "Uko free kesho?"),
        P2("Ramène tes amis", "Bring your friends", "Leta marafiki zako", "Leta mabeshte"),
        P2("On se voit demain ?", "See you tomorrow?", "Tutaonana kesho?", null, null, "A2"),
        P2("C'était génial hier !", "Yesterday was awesome!", "Jana ilikuwa kali!", "Jana ilikuwa kali!", null, null, "A2"),
        P2("C'est la fête !", "It's party time!", "Ni sherehe!", "Ni party!"),
        P2("Joyeux anniversaire !", "Happy birthday!", "Heri ya siku ya kuzaliwa!", "Happy birthday!"),
        P2("Bonne année !", "Happy New Year!", "Heru ya mwaka mpya!"),
        P2("Bon voyage mon ami !", "Safe travels my friend!", "Safari njema beshte!"),
        P2("Tu me manques", "I miss you", "Nakumiss", null, "Literally 'you are missing to me' — backwards from English.", "A2"),
        P2("Tu me manques trop", "I miss you so much", "Nakumiss sana"),
        P2("Présente-moi à tes amis", "Introduce me to your friends", "Nitambulishe kwa marafiki zako", null, null, "B1"),
        P2("Félicitations !", "Congratulations!", "Hongera!", null, null, null, "A2", true),
        P2("Bon courage !", "Good luck / hang in there!", "Kila la kheri!", null, "Means more 'keep going' than 'good luck'.", "A2"),
        P2("Ne t'inquiète pas", "Don't worry", "Usijali", null, null, "A2"),
        P2("Prends soin de toi", "Take care of yourself", "Jitunze", "Jitunze"),
        P2("On s'appelle !", "Let's call each other!", "Tupigiane!", "Tupigiane!"),
        P2("Écris-moi !", "Write to me!", "Niandikie!"),
        P2("Réponds-moi !", "Reply to me!", "Nijibu!"),
        P2("T'es le meilleur !", "You're the best!", "Wewe ni bora!", "Wewe ni best!"),
        P2("On reste en contact", "Let's stay in touch", "Tuendelee kuwasiliana", null, null, "B1"),
        P2("Gros câlin !", "Big hug!", "Nakukumbatia!", "Hug!"),
        P2("À la prochaine fête !", "Till the next party!", "Hadi sherehe ijayo!")
    ), "u5"),
    Lesson("daystory", "📖", "Raconter sa journée", "Talking about your day", "Kusimulia siku", listOf(
        P2("Ce matin je me suis levé tôt", "This morning I woke up early", "Asubuhi niliamka mapema", null, "Reflexive verb: se lever.", "A2"),
        P2("Je me suis douché", "I showered", "Nilioga", null, null, "A2"),
        P2("J'ai pris mon petit-déjeuner", "I had breakfast", "Nilikula kifungua kinywa"),
        P2("Ensuite j'ai pris un matatu", "Then I took a matatu", "Kisha nilipanda matatu", null, null, null, "A2", true),
        P2("Dans le matatu il y avait du monde", "The matatu was packed", "Kulikuwa na watu wengi kwa matatu"),
        P2("Je suis parti au travail", "I left for work", "Nilikwenda kazini", null, "Partir takes être.", "A2"),
        P2("Au travail on a eu une réunion", "At work we had a meeting", "Kazini tulikuwa na kikao", null, null, "A2"),
        P2("Mon chef m'a appelé", "My boss called me", "Bosi alinipigia"),
        P2("On a bien rigolé", "We had a good laugh", "Tulicheka sana", "Tulicheka mob", null, null, "A2"),
        P2("À midi j'ai mangé du pilau", "At noon I ate pilau", "Mchana nilikula pilau", null, null, "A2"),
        P2("J'ai rencontré un vieil ami", "I met an old friend", "Nilikutana na rafiki wa zamani", null, null, "B1"),
        P2("On a pris un café ensemble", "We had a coffee together", "Tulikunywa kahawa pamoja"),
        P2("Il m'a raconté ses nouvelles", "He told me his news", "Aliniambia habari zake"),
        P2("Ensuite je suis allé au marché", "Then I went to the market", "Kisha nilienda sokoni"),
        P2("J'ai acheté des légumes", "I bought vegetables", "Nilinunua mboga"),
        P2("Le vendeur m'a fait un bon prix", "The seller gave me a good price", "Muuzaji alinipunguzia"),
        P2("L'après-midi a passé vite", "The afternoon went fast", "Mchana ulipita haraka", null, null, "B1"),
        P2("Je suis rentré à pied", "I walked home", "Nilirudi kwa miguu", null, null, "A2"),
        P2("Les enfants jouaient dehors", "The kids were playing outside", "Watoto walikuwa wanacheza nje", null, "Imparfait for background scenes.", "B1"),
        P2("Puis je suis rentré fatigué", "Then I came home tired", "Kisha nilirudi nimechoka", null, "Rentrer uses être in passé composé.", "B1"),
        P2("Ma mère m'a appelé", "My mum called me", "Mama alinipigia"),
        P2("On a parlé longtemps", "We talked for a long time", "Tuliongea kwa muda mrefu"),
        P2("Le soir j'ai regardé un match", "In the evening I watched a match", "Jioni niliangalia mechi", null, null, "A2"),
        P2("Il n'y avait rien d'intéressant", "There was nothing interesting on", "Hakukuwa na kitu kinachovutia", null, null, "B1"),
        P2("Je me suis couché tôt", "I went to bed early", "Nililala mapema", null, null, "A2"),
        P2("Demain sera un autre jour !", "Tomorrow is another day!", "Kesho ni siku nyingine!"),
        P2("Quelle journée !", "What a day!", "Siku gani!", null, null, "A2")
    ), "u5"),
    Lesson("debate", "🗣️", "Débattre", "Debating lightly", "Kujadili", listOf(
        P2("Le foot d'abord !", "Football first!", "Mpira kwanza!", "Ball kwanza!"),
        P2("Mon équipe est la meilleure", "My team is the best", "Timu yangu ni bora", null, null, "B1"),
        P2("À mon avis le Real est meilleur", "In my opinion Real is better", "Kwa maoni yangu Real ni bora", null, null, "B1"),
        P2("Pas vraiment, Barça joue mieux", "Not really, Barça plays better", "Sio kweli, Barça inacheza vizuri", null, "Pas vraiment = polite pushback.", "B1"),
        P2("Tu rigoles ?!", "Are you kidding?!", "Unatania?!", "Unatania?!"),
        P2("Sérieusement ?", "Seriously?", "Kwa uzito?", "Seriously?"),
        P2("Écoute-moi bien", "Listen to me well", "Nisikilize vizuri"),
        P2("Laisse-moi finir", "Let me finish", "Niachie nimalize"),
        P2("Je suis d'accord avec toi", "I agree with you", "Nakubaliana nawe", null, null, null, "A2", true),
        P2("Je ne suis pas convaincu", "I'm not convinced", "Sijashawishika"),
        P2("Prouve-le !", "Prove it!", "Thibitisha!"),
        P2("Les chiffres parlent", "Numbers don't lie", "Takwimu zinaongea"),
        P2("Regarde les trophées", "Look at the trophies", "Angalia makombe"),
        P2("Mais pense aux statistiques", "But think about the stats", "Lakini fikiria takwimu", null, null, "B1"),
        P2("On parie ?", "Wanna bet?", "Tuweke dau?", "Tuweke bet?"),
        P2("Pari tenu !", "Bet accepted!", "Dau limekubaliwa!"),
        P2("Tu vas perdre", "You're going to lose", "Utashindwa", "Utashindwa", "Say it grinning, or else!"),
        P2("On verra bien", "We'll see", "Tutaona"),
        P2("Que le meilleur gagne !", "May the best win!", "Bora ashinde!"),
        P2("On est d'accord pour ne pas être d'accord", "Let's agree to disagree", "Tukubali kutokubaliana", null, null, "B1"),
        P2("Tu as peut-être raison", "You may be right", "Labda uko sahihi"),
        P2("D'accord, tu as gagné cette fois", "Okay, you won this time", "Sawa, umeshinda safari hii"),
        P2("Match nul !", "Draw!", "Sare!"),
        P2("On est quittes !", "We're even!", "Tuko sawa!"),
        P2("Sans rancune ?", "No hard feelings?", "Bila chuki?"),
        P2("On reste amis ?", "We're still friends?", "Bado marafiki?"),
        P2("Je vois ce que tu veux dire", "I see what you mean", "Naelewa unachomaanisha", null, null, "B1"),
        P2("Changeons de sujet", "Let's change the subject", "Tubadilishe mada", null, null, "A2"),
        P2("Le foot kenyan monte en puissance", "Kenyan football is on the rise", "Mpira wa Kenya unapanda", null, null, "B1"),
        P2("C'était un bon débat !", "That was a good debate!", "Ilikuwa mjadala mzuri!"),
        P2("La revanche la semaine prochaine !", "Rematch next week!", "Marudiano wiki ijayo!")
    ), "u5"),
    Lesson("reviewa2", "🔁", "Révision A2", "A2 review", "Marudio", listOf(
        P2("Je voudrais réserver une table", "I'd like to book a table", "Ningependa kuweka meza", null, null, null, "A2", true),
        P2("Nous avons visité le marché hier", "We visited the market yesterday", "Tulitembelea soko jana", null, null, "A2"),
        P2("Elle va nous rejoindre plus tard", "She'll join us later", "Atajiunga nasi baadaye", null, "Futur proche: aller + infinitive.", "A2"),
        P2("Il n'y a plus de pain", "There's no more bread", "Hakuna mkate tena", null, "Ne…plus = no more.", "A2"),
        P2("Tu connais un bon restaurant ?", "Do you know a good restaurant?", "Unajua mgahawa mzuri?", null, "Connaître (people/places) vs savoir (facts).", "A2"),
        P2("On y va ensemble ?", "Shall we go together?", "Twende pamoja?", null, "Y = there.", null, "A2", true),
        P2("J'en veux deux", "I want two of them", "Nataka mbili", null, "En replaces 'of it/them'.", "B1"),
        P2("Je vais te montrer", "I'll show you", "Nitakuonyesha"),
        P2("Regarde bien", "Look carefully", "Angalia vizuri"),
        P2("Écoute bien", "Listen carefully", "Sikiliza vizuri"),
        P2("Répète après moi", "Repeat after me", "Rudia nyuma yangu"),
        P2("Encore une fois", "One more time", "Tena mara moja", "Tena!"),
        P2("Plus lentement", "More slowly", "Polepole zaidi"),
        P2("Tu comprends ?", "Do you understand?", "Unaelewa?", null, null, "A2"),
        P2("Oui, je comprends", "Yes, I understand", "Ndio, naelewa"),
        P2("Non, pas encore", "No, not yet", "Bado"),
        P2("Presque !", "Almost!", "Karibu!"),
        P2("Exactement !", "Exactly!", "Hasa!", "Exactly!"),
        P2("C'est ça !", "That's it!", "Ndiyo hivyo!"),
        P2("Bien vu !", "Well spotted!", "Umeona poa!"),
        P2("Pas mal !", "Not bad!", "Si mbaya!"),
        P2("Continue comme ça !", "Keep it up!", "Endelea hivyo!"),
        P2("Tu progresses vite !", "You're progressing fast!", "Unaendelea haraka!"),
        P2("Je suis fier de toi !", "I'm proud of you!", "Najivunia wewe!"),
        P2("On recommence ?", "Shall we restart?", "Tuanze tena?"),
        P2("Dernier essai !", "Last try!", "Jaribio la mwisho!"),
        P2("Tu as réussi !", "You did it!", "Umefanikiwa!", null, null, null, "A2", true)
    ), "u6"),
    Lesson("bridgeb1", "🌉", "Vers B1", "Bridging to B1", "Kuelekea B1", listOf(
        P2("Si j'avais le temps, je voyagerais", "If I had time, I'd travel", "Kama ningekuwa na muda, ningesafiri", null, "Si + imparfait → conditionnel.", "B1"),
        P2("Quand je serai à Paris", "When I'm in Paris (one day)", "Nitakapokuwa Paris", null, "Future after quand.", "B1"),
        P2("Raconte-moi tout", "Tell me everything", "Niambie kila kitu", null, null, null, "B1", true),
        P2("Je n'y avais jamais pensé", "I'd never thought of it", "Sikuwahi kufikiria hivyo", null, null, "B1"),
        P2("Il faut que je parte", "I have to go", "Lazima niende", null, "Falloir que + subjunctive.", "B1"),
        P2("Quoi qu'il arrive", "Whatever happens", "Chochote kitakachotokea", null, "Subjunctive trigger.", "B1"),
        P2("Où que tu ailles", "Wherever you go", "Popote uendapo", null, null, "B1"),
        P2("Bien que ce soit difficile", "Although it's hard", "Ingawa ni ngumu", null, "Bien que + subjunctive.", "B1"),
        P2("Pour que tu comprennes", "So that you understand", "Ili uelewe"),
        P2("Avant que je parte", "Before I leave", "Kabla sijaondoka", null, null, "B1"),
        P2("Sans que personne sache", "Without anyone knowing", "Bila mtu kujua"),
        P2("Il se peut que", "It may be that", "Inawezekana"),
        P2("Il est possible que", "It's possible that", "Inawezekana"),
        P2("Ce qui compte, c'est d'essayer", "What matters is trying", "Muhimu ni kujaribu", null, null, "B1"),
        P2("Il est temps de partir", "It's time to go", "Ni wakati wa kuondoka"),
        P2("À force de pratiquer", "By dint of practising", "Kwa kujizoeza", null, null, "B1"),
        P2("Petit à petit", "Little by little", "Kidogo kidogo", "Mora mora"),
        P2("Rome ne s'est pas faite en un jour", "Rome wasn't built in a day", "Roma haikujengwa kwa siku moja"),
        P2("Qui vivra verra", "Time will tell", "Muda utaonyesha", "Time will tell"),
        P2("Tant pis !", "Too bad! / never mind!", "Potelea mbali!", "Whatever!"),
        P2("Tant mieux !", "Great! / all the better!", "Vizuri zaidi!"),
        P2("Ça vaut le coup !", "It's worth it!", "Inafaa!", "Worth it!"),
        P2("Chiche !", "You're on! / dare!", "Kubali!", "Bet!"),
        P2("Marché conclu !", "Deal!", "Kubaliana!", "Deal!"),
        P2("On y va ?", "Shall we go?", "Twende?", null, null, null, "A2", true),
        P2("J'ai hâte", "I can't wait", "Nasubiri kwa hamu", null, null, "B1"),
        P2("Santé et réussite !", "Health and success!", "Afya na mafanikio!"),
        P2("L'avenir t'appartient !", "The future is yours!", "Baadaye ni yako!")
    ), "u6", culture = "French opens doors well beyond France: Nairobi's Alliance Française, universities in Dakar, Abidjan and Kigali, and regional organisations all run partly in French — a Kenyan with real spoken French stands out fast."),
    Lesson("slang", "🔥", "L'argot", "French slang", "Slang ya Kifaransa", listOf(
        P2("Un pote", "A buddy", "Rafiki", "Beshte", null, null, "A1", true),
        P2("Meuf", "Girl / woman (verlan)", "Msichana", "Manzi", "Verlan flips syllables: femme → meuf. Friends only!"),
        P2("Ouf", "Crazy / insane (verlan)", "Kichaa", "Wazimu", "Fou → ouf. 'C'est ouf !' = that's insane!"),
        P2("Chelou", "Weird / shady (verlan)", "Ajabu", "Weird", "Louche → chelou."),
        P2("Relou", "Annoying", "Msumbufu", "Msumbufu", "Lourd → relou. 'T'es relou !' — only with close friends!"),
        P2("Kiffer", "To love / be into", "Kupenda sana", "Kupenda", "Je kiffe ce son !"),
        P2("Grave", "Totally / seriously", "Kabisa", "Kabisa", "Adds emphasis: 'C'est grave bon !'"),
        P2("Trop", "So / too (very)", "Sana", "Sana", "Trop bien ! = so good!"),
        P2("Carrément", "Totally / absolutely", "Kabisa", "Kabisa"),
        P2("Franchement", "Honestly", "Ukweli", "Ukweli"),
        P2("Bosser", "To work (hard)", "Kufanya kazi", "Kuhustle", "Je bosse dur."),
        P2("Bouffer", "To eat (casual)", "Kula", "Kula", "On bouffe quoi ce soir ?"),
        P2("Rigoler", "To laugh / joke", "Kucheka", "Kucheka", null, null, "A2"),
        P2("Se marrer", "To have a laugh", "Kucheka sana", "Kucheka"),
        P2("Chouette", "Nice / cool", "Nzuri", "Poa", "Une chouette soirée !"),
        P2("Nickel", "Perfect / spotless", "Kamili", "Fiti", "C'est nickel !"),
        P2("Laisser tomber", "Forget it / drop it", "Achana nayo", "Achana nayo"),
        P2("C'est nul", "That sucks", "Haina maana", "Ni upuss", "Playful complaint among friends."),
        P2("N'importe quoi !", "Whatever! / Nonsense!", "Upuuzi!", "Upuzi!"),
        P2("T'inquiète", "Don't worry", "Usijali", "Usijali", null, null, "A2", true),
        P2("Vas-y !", "Go on! / Go for it!", "Twende!", "Twende!", null, null, "A2", true),
        P2("Une bagnole", "A car (slang)", "Gari", "Gari", "Ma bagnole est en panne."),
        P2("Avoir la flemme", "To feel lazy", "Kuwa mvivu", "Kuwa lazy", "J'ai la flemme de sortir."),
        P2("C'est chanmé ?", "Is it cool? (verlan)", "Ni poa?", "Ni poa?", "Méchant → chanmé. Yes, 'mean' became 'cool'.")
    ), "u5", culture = "Verlan (backwards slang) was born in Paris banlieues and now lives in French rap your matatu probably already plays — Niska, MHD, Dadju. Slang is friendship glue: use it with friends, never in a job interview or with officials."),
    Lesson("roast", "😈", "Vannes entre amis", "Friendly roasts", "Kuchomana kistaarabu", listOf(
        P2("Andouille !", "You goof!", "Mjinga mdogo!", "Msee!", "Silly, never cruel — the classic friendly jab.", null, "A2"),
        P2("Tête de linotte !", "Birdbrain!", "Kichwa cha ndege!", null, "Linotte = a little bird. Adorable, not mean.", null, "A2"),
        P2("Espèce de chamallow !", "You marshmallow!", "Wewe ni laini!", null, "Calling someone soft and sweet. Peak gentle roast.", null, "A2"),
        P2("Cornichon !", "You pickle!", "Wewe ni tangawizi!", null, "Yes, really — a beloved silly insult.", null, "A2"),
        P2("Tête en l'air !", "Airhead! (dreamy)", "Mwenye ndoto!", null, "For the friend always daydreaming in lectures.", null, "A2"),
        P2("Gros malin !", "Smart aleck!", "Mjanja!", "Mjanja!", "Said with a grin when a friend shows off.", null, "A2"),
        P2("Petit malin !", "Clever little thing!", "Kijana mjanja!", null, null, "A2"),
        P2("Sacré farceur !", "You prankster!", "Mcheshi!", null, null, "B1"),
        P2("Tu es lent comme un escargot pressé", "You're slow like a hurried snail", "Wewe ni mpole kama konokono", null, "Absurd on purpose — that's what makes it funny.", "B1"),
        P2("Ton accent est comme le pilau sans épices", "Your accent is like pilau with no spices", "Lafudhi yako ni kama pilau bila viungo", null, "Food roasts always land in Kenya.", "B1"),
        P2("Tu cours comme une girafe en tongs", "You run like a giraffe in flip-flops", "Unakimbia kama twiga na kandambili", null, null, "B1"),
        P2("Tête de pioche !", "You pickaxe-head! (stubborn)", "Mkaidi!", null, "For friendly stubbornness only.", null, "B1"),
        P2("Vilain !", "Naughty! (playful)", "Mtundu!", null, "What French aunties say pinching cheeks — pure affection.", null, "A2"),
        P2("Canaille !", "Rascal! (affectionate)", "Mjanja mdogo!", null, null, "B1"),
        P2("Coquin !", "Cheeky!", "Mcheshi!", null, null, "A2"),
        P2("Mon petit chou", "My little cabbage (sweetie)", "Mpenzi wangu", null, "Cabbage = term of endearment. French is weird. Embrace it.", null, "A2"),
        P2("Tu parles comme un matatu sans freins", "You talk like a matatu with no brakes", "Unaongea kama matatu bila breki", null, "Fast, loud, unstoppable — take it as a compliment.", "B1"),
        P2("Champion du monde de la sieste !", "World champion of napping!", "Bingwa wa usingizi!", null, null, "A2"),
        P2("Roi de la dernière minute !", "King of last-minute!", "Mfalme wa dakika za mwisho!", null, "For the friend who submits assignments at 11:59pm.", "B1"),
        P2("On t'aime quand même !", "We love you anyway!", "Tunakupenda hivyo hivyo!", "Tunakupenda hivyo!", "The golden rule: every roast ends with love.", null, "A2", true)
    ), "u5", culture = "La vanne (banter) is sacred among French friends — but the rules are strict: roast friends, never strangers; punch at effort and habits, never at bodies, families or backgrounds; and always land with love ('on t'aime quand même'). Break these and you're not funny, you're just rude.")
)

// §5.7 minimal pairs: sounds that don't exist in English/Kiswahili phonology
data class MinimalPair(val a: String, val meanA: String, val b: String, val meanB: String)

val MINIMAL_PAIRS: List<MinimalPair> = listOf(
    MinimalPair("tu", "you", "tout", "all / everything"),
    MinimalPair("ou", "or", "où", "where"),
    MinimalPair("ces", "these", "ses", "his / her"),
    MinimalPair("pain", "bread", "bain", "bath"),
    MinimalPair("rue", "street", "roue", "wheel"),
    MinimalPair("mer", "sea", "mère", "mother"),
    MinimalPair("dessous", "underneath", "dessus", "on top"),
    MinimalPair("jeune", "young", "jaune", "yellow"),
    MinimalPair("poisson", "fish", "poison", "poison"),
    MinimalPair("vert", "green", "verre", "glass")
)

// §5.12 story mode: micro-stories from known vocabulary + comprehension questions
data class StoryQ(val text: String, val options: List<String>, val answer: String)
data class Story(val id: String, val unitId: String, val title: String, val sentences: List<String>, val questions: List<StoryQ>)

val STORIES: List<Story> = listOf(
    Story("story-u1", "u1", "Le premier jour", listOf(
        "Amina arrive à Nairobi.",
        "Elle dit bonjour à tout le monde.",
        "Elle compte jusqu'à dix en français.",
        "Le soir, elle dit au revoir et à demain."
    ), listOf(
        StoryQ("How does Amina greet people?", listOf("Bonjour", "Au revoir", "Merci"), "Bonjour"),
        StoryQ("What does she do in the evening?", listOf("She says goodbye", "She counts", "She eats"), "She says goodbye")
    )),
    Story("story-u2", "u2", "Le marché", listOf(
        "Samedi, Fatou va au marché avec sa mère.",
        "Il fait beau et il y a beaucoup de monde.",
        "Elle achète du pain et des fruits.",
        "Le soir, toute la famille mange ensemble."
    ), listOf(
        StoryQ("When does Fatou go to the market?", listOf("Saturday", "Monday", "Sunday"), "Saturday"),
        StoryQ("What does she buy?", listOf("Bread and fruit", "Fish and rice", "Milk and eggs"), "Bread and fruit")
    )),
    Story("story-u3", "u3", "Le match", listOf(
        "Dimanche, Otis regarde un match avec ses amis.",
        "Il écoute de la musique avant le match.",
        "Son équipe gagne deux à zéro.",
        "C'est génial, tout le monde est content."
    ), listOf(
        StoryQ("Who does Otis watch with?", listOf("His friends", "His family", "His teacher"), "His friends"),
        StoryQ("What is the score?", listOf("Two to zero", "One to zero", "Three to one"), "Two to zero")
    )),
    Story("story-u4", "u4", "Perdu en ville", listOf(
        "Un touriste est perdu dans une grande ville.",
        "Il demande son chemin à une dame.",
        "Elle dit : continuez tout droit, puis à gauche.",
        "Cinq minutes plus tard, il trouve son hôtel."
    ), listOf(
        StoryQ("Who does he ask?", listOf("A lady", "A policeman", "A driver"), "A lady"),
        StoryQ("How long does it take?", listOf("Five minutes", "Ten minutes", "One hour"), "Five minutes")
    )),
    Story("story-u5", "u5", "Le débat", listOf(
        "Deux amis débattent : Real ou Barça ?",
        "L'un dit que le Real est meilleur.",
        "L'autre n'est pas d'accord.",
        "À la fin, ils rient et restent amis."
    ), listOf(
        StoryQ("What do they debate?", listOf("Real or Barça", "Food", "Music"), "Real or Barça"),
        StoryQ("How does it end?", listOf("They laugh and stay friends", "They fight", "One leaves"), "They laugh and stay friends")
    )),
    Story("story-u6", "u6", "Le voyage", listOf(
        "Si elle avait le temps, Amina voyagerait partout.",
        "Quand elle sera à Dakar, elle parlera français tous les jours.",
        "Elle racontera tout à sa famille.",
        "Ce qui compte, c'est d'essayer."
    ), listOf(
        StoryQ("Where will she speak French daily?", listOf("Dakar", "Paris", "Nairobi"), "Dakar"),
        StoryQ("What matters, according to the story?", listOf("Trying", "Winning", "Waiting"), "Trying")
    ))
)

fun storyForUnit(unitId: String): Story? = STORIES.find { it.unitId == unitId }
