package com.francofun.content

val FRENCH_SONGS: List<Song> by lazy {
    listOf(
        Song("1","Tout oublié","Stromae", "Electro-pop", 2022,
            "Tout oublié, tout oublié\nOn s'en va, on s'en va\nLes souvenirs s'en vont\nTout oublié, tout oublié",
            "Everything forgotten, everything forgotten\nWe go, we go\nMemories go away\nEverything forgotten"),
        Song("2","Fils de joie","Stromae", "Electro-pop", 2022,
            "Fils de joie, fils de joie\nOn est tous des fils de joie\nFils de joie, fils de joie\nOn danse jusqu'à la nuit",
            "Sons of joy, sons of joy\nWe are all sons of joy\nSons of joy, sons of joy\nWe dance until the night"),
        Song("3","L'enfer","Stromae", "Electro-pop", 2022,
            "L'enfer, l'enfer\nC'est là où on va tous\nL'enfer, l'enfer\nMais on n'y fait pas tous",
            "Hell, hell\nIt's where we all go\nHell, hell\nBut not all of us do"),
        Song("4","Santé","Stromae", "Electro-pop", 2021,
            "Santé, santé\nOn boit à ta santé\nSanté, santé\nPour oublier nos peines",
            "Health, health\nWe drink to your health\nHealth, health\nTo forget our sorrows"),
        Song("5","Mon amour","Stromae", "Electro-pop", 2022,
            "Mon amour, mon amour\nTu es tout ce que j'ai\nMon amour, mon amour\nNe me laisse pas",
            "My love, my love\nYou are everything I have\nMy love, my love\nDon't leave me"),
        Song("6","Défiler","Stromae", "Electro-pop", 2018,
            "Défiler, défiler\nUnder control\nDéfiler, défiler\nOn défile tous",
            "March, march\nUnder control\nMarch, march\nWe all march"),
        Song("7","Papaoutai","Stromae", "Electro-pop", 2013,
            "Papaoutai, papaoutai\nDis-moi c'est où c'est ton papa\nPapaoutai, papaoutai\nOù tu es, papa",
            "Papaoutai, papaoutai\nTell me where your daddy is\nPapaoutai, papaoutai\nWhere are you, daddy"),
        Song("8","Formidable","Stromae", "Electro-pop", 2014,
            "Formidable, formidable\nJe suis formidable\nFormidable, formidable\nTous ensemble",
            "Incredible, incredible\nI am incredible\nIncredible, incredible\nAll together"),
        Song("9","Avise-moi","Stromae", "Electro-pop", 2014,
            "Avise-moi, avise-moi\nTu me plais tant\nAvise-moi, avise-moi\nDis-moi ce que tu veux",
            "Look at me, look at me\nYou please me so much\nLook at me, look at me\nTell me what you want"),
        Song("10","Ta reine","Stromae", "Electro-pop", 2022,
            "Ta reine, ta reine\nJe suis ta reine\nTa reine, ta reine\nSuis-moi",
            "Your queen, your queen\nI am your queen\nYour queen, your queen\nFollow me"),
        Song("11","Dernière danse","Indila", "Pop", 2014,
            "Dernière danse, dernière danse\nJe veux encore danser\nDernière danse, dernière danse\nAvant que tout s'arrête",
            "Last dance, last dance\nI want to dance again\nLast dance, last dance\nBefore everything stops"),
        Song("12","Tourner dans le vide","Indila", "Pop", 2014,
            "Tourner dans le vide, tourner dans le vide\nJe tourne sans fin\nTourner dans le vide, tourner dans le vide\nJusqu'à ce que je tombe",
            "Spinning in the void, spinning in the void\nI spin endlessly\nSpinning in the void, spinning in the void\nUntil I fall"),
        Song("13","S.O.S. d'un terrien en détresse","Indila", "Pop", 2014,
            "S.O.S. d'un terrien en détresse\nS.O.S. d'un cœur qui bat\nS.O.S. d'un monde qui tremble\nS.O.S. de nous",
            "S.O.S. of a human in distress\nS.O.S. of a beating heart\nS.O.S. of a trembling world\nS.O.S. of us"),
        Song("14","Parle à ta tête","Indila", "Pop", 2019,
            "Parle à ta tête, parle à ta tête\nDis-lui ce que tu ressens\nParle à ta tête, parle à ta tête\nNe reste pas avec ça",
            "Talk to your head, talk to your head\nTell it what you feel\nTalk to your head, talk to your head\nDon't keep it inside"),
        Song("15","Mini-World","Indila", "Pop", 2014,
            "Mini-world, mini-world\nDans mon petit monde\nMini-world, mini-world\nTout est si petit",
            "Mini-world, mini-world\nIn my little world\nMini-world, mini-world\nEverything is so small"),
        Song("16","Tu ne sais pas","Indila", "Pop", 2014,
            "Tu ne sais pas, tu ne sais pas\nCe que j'ai pour toi\nTu ne sais pas, tu ne sais pas\nCe que je porte en moi",
            "You don't know, you don't know\nWhat I have for you\nYou don't know, you don't know\nWhat I carry in me"),
        Song("17","Feuille d'automne","Indila", "Pop", 2014,
            "Feuille d'automne, feuille d'automne\nTu tombes doucement\nFeuille d'automne, feuille d'automne\nSur mon cœur qui bat",
            "Autumn leaf, autumn leaf\nYou fall softly\nAutumn leaf, autumn leaf\nOn my beating heart"),
        Song("18","Comme des enfants","Cœur de Pirate", "Indie pop", 2011,
            "Comme des enfants, comme des enfants\nOn s'aime comme des enfants\nComme des enfants, comme des enfants\nSans rien comprendre",
            "Like children, like children\nWe love like children\nLike children, like children\nWithout understanding"),
        Song("19","Adieu","Cœur de Pirate", "Indie pop", 2011,
            "Adieu, adieu\nOn se dit adieu\nAdieu, adieu\nMais je pense à toi",
            "Goodbye, goodbye\nWe say goodbye\nGoodbye, goodbye\nBut I think of you"),
        Song("20","Saint-Laurent","Cœur de Pirate", "Indie pop", 2011,
            "Saint-Laurent, Saint-Laurent\nDans la rue Saint-Laurent\nSaint-Laurent, Saint-Laurent\nOn y vit la nuit",
            "Saint-Laurent, Saint-Laurent\nOn Saint-Laurent street\nSaint-Laurent, Saint-Laurent\nWe live there at night"),
        Song("21","Trop tôt","Cœur de Pirate", "Indie pop", 2011,
            "Trop tôt, trop tôt\nOn s'est connus trop tôt\nTrop tôt, trop tôt\nMaintenant je sais",
            "Too early, too early\nWe met too early\nToo early, too early\nNow I know"),
        Song("22","Oublie-moi","Cœur de Pirate", "Indie pop", 2011,
            "Oublie-moi, oublie-moi\nOublie ce qu'on a été\nOublie-moi, oublie-moi\nEt commence encore",
            "Forget me, forget me\nForget what we were\nForget me, forget me\nAnd start again"),
        Song("23","Je te promets","Johnny Hallyday", "Rock", 1975,
            "Je te promets, je te promets\nDes nuits sans fin\nJe te promets, je te promets\nJusqu'à la fin",
            "I promise you, I promise you\nEndless nights\nI promise you, I promise you\nUntil the end"),
        Song("24","La musique que j'aime","Johnny Hallyday", "Rock", 1974,
            "La musique que j'aime\nEst dans tes yeux\nLa musique que j'aime\nC'est toi et moi",
            "The music I love\nIs in your eyes\nThe music I love\nIs you and me"),
        Song("25","Diego","Johnny Hallyday", "Rock", 1991,
            "Diego, Diego\nTon nom résonne\nDiego, Diego\nDans ma mémoire",
            "Diego, Diego\nYour name resonates\nDiego, Diego\nIn my memory"),
        Song("26","Toujours là pour toi","M. Pokora", "Pop", 2015,
            "Toujours là pour toi, toujours là\nJe ne te laisserai jamais\nToujours là pour toi, toujours là\nQuoi qu'il arrive",
            "Always here for you, always here\nI'll never leave you\nAlways here for you, always here\nWhatever happens"),
        Song("27","Envole-moi","M. Pokora", "Pop", 2012,
            "Envole-moi, envole-moi\nDans le ciel bleu\nEnvole-moi, envole-moi\nPlus haut que tout",
            "Fly me, fly me\nInto the blue sky\nFly me, fly me\nHigher than everything"),
        Song("28","Les planètes","M. Pokora", "Pop", 2015,
            "Les planètes, les planètes\nDansent dans la nuit\nLes planètes, les planètes\nÉclairent nos vies",
            "The planets, the planets\nDance in the night\nThe planets, the planets\nLight up our lives"),
        Song("29","Si tu pars","Grand Corps Malade", "Chanson", 2006,
            "Si tu pars, si tu pars\nLe monde s'efface\nSi tu pars, si tu pars\nIl n'y a plus rien",
            "If you leave, if you leave\nThe world fades away\nIf you leave, if you leave\nThere is nothing left"),
        Song("30","Chez Laurette","Grand Corps Malade", "Chanson", 2006,
            "Chez Laurette, chez Laurette\nOn partage nos rires\nChez Laurette, chez Laurette\nC'est notre monde",
            "At Laurette's, at Laurette's\nWe share our laughter\nAt Laurette's, at Laurette's\nIt's our world"),
        Song("31","1, 2, 3","Nolwenn Leroy", "Pop", 2003,
            "Un, deux, trois, je te compte\nUn, deux, trois, attends-moi\nUn, deux, trois, va vite\nNe me quitte pas",
            "One, two, three, I count you\nOne, two, three, wait for me\nOne, two, three, hurry\nDon't leave me"),
        Song("32","Cassé","Nolwenn Leroy", "Pop", 2003,
            "Cassé, cassé\nMon cœur est cassé\nCassé, cassé\nPar ton regard",
            "Broken, broken\nMy heart is broken\nBroken, broken\nBy your gaze"),
        Song("33","Incontournable","Nolwenn Leroy", "Pop", 2003,
            "Incontournable, incontournable\nTon sourire me poursuit\nIncontournable, incontournable\nDans chaque jour",
            "Unavoidable, unavoidable\nYour smile follows me\nUnavoidable, unavoidable\nIn every day"),
        Song("34","La pluie","Aldebert", "Chanson", 2015,
            "La pluie, la pluie\nTombe sur la ville\nLa pluie, la pluie\nLave nos peines",
            "The rain, the rain\nFalls on the city\nThe rain, the rain\nWashes our sorrows"),
        Song("35","Promenons-nous dans les bois","Collectif Métissé", "Zouk", 2015,
            "Promenons-nous dans les bois\nComme on promène nos chiens\nPromenons-nous dans les bois\nComme on promène nos chiens",
            "Let's walk in the woods\nLike we walk our dogs\nLet's walk in the woods\nLike we walk our dogs"),
        Song("36","Li Tourner","Lartiste", "Afro-beat", 2015,
            "Li tourner, li tourner\nOn tourne ensemble\nLi tourner, li tourner\nPour toujours",
            "Let's turn, let's turn\nWe turn together\nLet's turn, let's turn\nForever"),
        Song("37","Marly-Gomont","Kamini", "Hip-hop", 2006,
            "Marly-Gomont, Marly-Gomont\nC'est mon village\nMarly-Gomont, Marly-Gomont\nC'est ma fierté",
            "Marly-Gomont, Marly-Gomont\nIt's my village\nMarly-Gomont, Marly-Gomont\nIt's my pride"),
        Song("38","Déconnectés","Humphrey", "Electro", 2015,
            "Déconnectés, déconnectés\nPlus de réseau\nDéconnectés, déconnectés\nOn est ensemble",
            "Disconnected, disconnected\nNo more network\nDisconnected, disconnected\nWe are together"),
        Song("39","On n'est pas des anges","Lara Fabian", "Pop", 2000,
            "On n'est pas des anges\nMais on vole quand même\nOn n'est pas des anges\nOn s'envole ensemble",
            "We are not angels\nBut we still fly\nWe are not angels\nWe fly together"),
        Song("40","Je t'aime","Lara Fabian", "Pop", 1997,
            "Je t'aime, je t'aime\nComme le ciel aime la terre\nJe t'aime, je t'aime\nPour toujours",
            "I love you, I love you\nLike the sky loves the earth\nI love you, I love you\nForever"),
        Song("41","Tandem","Vanessa Paradis", "Pop", 1987,
            "Tandem, tandem\nSur la route de l'amour\nTandem, tandem\nMain dans la main",
            "Tandem, tandem\nOn the road of love\nTandem, tandem\nHand in hand"),
        Song("42","Joe le taxi","Vanessa Paradis", "Pop", 1987,
            "Joe le taxi\nPrend-moi la main\nJoe le taxi\nMène-moi loin",
            "Joe the taxi\nTake my hand\nJoe the taxi\nTake me far"),
        Song("43","La demoiselle","Charles Aznavour", "Chanson", 1990,
            "La demoiselle\nEst belle ce soir\nLa demoiselle\nMe regarde en silence",
            "The young lady\nIs beautiful tonight\nThe young lady\nLooks at me in silence"),
        Song("44","Hier encore","Charles Aznavour", "Chanson", 1964,
            "Hier encore\nTout était plus simple\nHier encore\nLe monde était beau",
            "Yesterday\nEverything was simpler\nYesterday\nThe world was beautiful"),
        Song("45","La Bohème","Charles Aznavour", "Chanson", 1966,
            "La Bohème\nUn peu de rêve\nLa Bohème\nLa vie en rose",
            "The Bohemian\nA little dream\nThe Bohemian\nLife in pink"),
        Song("46","Évidemment","France Gall", "Pop", 1988,
            "Évidemment\nC'est bien joli\nÉvidemment\nMais c'est un peu triste",
            "Of course\nIt's nice\nOf course\nBut it's a bit sad"),
        Song("47","Élsa","France Gall", "Pop", 1988,
            "Élsa, Élsa\nMon cœur bat\nÉlsa, Élsa\nPour toi je vis",
            "Elsa, Elsa\nMy heart beats\nElsa, Elsa\nFor you I live"),
        Song("48","N'oublie pas","Mylène Farmer", "Pop", 2015,
            "N'oublie pas\nNos années de jeunesse\nN'oublie pas\nNos rires et nos larmes",
            "Don't forget\nOur years of youth\nDon't forget\nOur laughter and our tears"),
        Song("49","Libertine","Mylène Farmer", "Pop", 1986,
            "Libertine\nJe suis libre\nLibertine\nDe mon cœur",
            "Libertine\nI am free\nLibertine\nOf my heart"),
        Song("50","Désenchantée","Mylène Farmer", "Pop", 1991,
            "Désenchantée\nLe monde est gris\nDésenchantée\nMais je crois encore",
            "Disenchanted\nThe world is grey\nDisenchanted\nBut I still believe")
    )
}
